### ISSUE TITLE
Implement Volume Snapshotting

### ISSUE THREAD

**Issue by rslinckx** [topolvm/topolvm#124]
First off, thanks for this awesome project!

## What

Are there any plans to support k8s Volume snapshotting with lvm snapshots, which would support various backup solutions in kubernetes relying on snapshots to be available ?

## How

Describe how to address the issue.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by tapih** [comment]
@rslinckx 
Thank you for your comment !!
I'm afraid we don't have any plan to support the volume snapshotting feature for now.
Your PR is always welcomed if you'd like to work on it, though.

**Comment by toshipp** [comment]
working on #385 #446

**Comment by huang339** [comment]
the problem is  how to recover quickly  from snapshot?

**Comment by jakobmoellerdev** [comment]
I just want to write here for anyone looking at this today or in the future: TopoLVM supports expiremental snapshots for Thinly Provisioned volumes.

**Comment by toshipp** [comment]
As mentioned above, we have a snapshot feature for thin volumes now.
For thick, it may be hard to implement as [denoted](https://github.com/topolvm/topolvm/blob/main/docs/limitations.md#snapshots-can-be-created-only-for-thin-volumes), so we have no plan to forward it.
