### ISSUE TITLE
Upgrade Path/Strategy

### ISSUE THREAD

**Issue by lz006** [topolvm/topolvm#139]
## What

Hello, thanks for your amazing project. We thinking about rolling out topolvm on our k8s clusters but could not find any hint regarding how to perform lvmd updates on a running cluster. Given there is a new release for lvmd, would it be possible to "retire" a node then update lvmd and let node join cluster back again? We know 0.X.X is a prerelease but of course getting stuck to specific release would be hairy. 

Thank you in advance for sharing your thoughts/recommendation regarding upgrade strategy.

Cheers.

## How

Describe how to address the issue.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by zoetrope** [comment]
Basically, lvmd is backward compatible, you can just replace lvmd binary and restart lvmd before upgrading other components.

However I am planning support for multiple volume groups #132, this change is not backwards compatible.
You need to follow the steps below.
https://github.com/cybozu-go/topolvm/blob/master/docs/proposals/multiple-volumegroups.md#upgrade--downgrade-strategy

**Comment by ymmt2005** [comment]
Thank you for raising the issue.  We should add the upgrade strategy before releasing 1.0.

**Comment by ymmt2005** [comment]
Through the experience in implementing the multiple volume group support in #125,
we learned that the following rule is critical for seamless upgrading.

- Old `lvmd` can work with new TopoLVM but w/o support for new features.
- New `lvmd` must work with old TopoLVM w/o any problem.

**Comment by kfox1111** [comment]
What is the reason for not running lvmd within a container managed by a daemonset?

**Comment by kfox1111** [comment]
Still interested in a solution to this... There a plan yet? There a reason not to put it into a container + daemonset? If not, I can give it a shot.

**Comment by ymmt2005** [comment]
We have no plan to make lvmd as DaemonSet.
If you are interested in adding DaemonSet option, please read  the [FAQ](../tree/master/docs/faq.md) first.

**Comment by kfox1111** [comment]
Thanks for the faq link.

I believe all the concerns in the faq can be mitigated by:
* shipping lvmd & nsenter in a container
* setting the lvmd pod to hostPID: true (so it can see pid1 on the host)
* setting the lvmd pod to be privileged (so it can use nsenter)
* mounting /bin or some other directory from the host into the container at /hostbin as writable
* copying lvmd to /hostbin
* running: nsenter -t 1 -a /bin/lvmd (startup lvmd on the host)

It should then run lvmd as if it was on the host as all the containerization will be stripped back to the namespaces associated with the hosts pid1 process.

**Comment by ymmt2005** [comment]
@kfox1111 
Would you create another issue to discuss that option?  Thank you.

**Comment by kfox1111** [comment]
Done. https://github.com/topolvm/topolvm/issues/195 :)

**Comment by toshipp** [comment]
Thanks to #195, we can update lvmd in a general k8s pod manner.
