### ISSUE TITLE
Install with Helm3

### ISSUE THREAD

**Issue by briantopping** [topolvm/topolvm#149]
## What

Please consider creating a Helm chart for installation

## How

Thank you for the very interesting project. But I wish it was easier to install after working a lot of hours. I feel like I might miss something important. 

Helm is great because it can generate a single manifest very quickly. I think it would help a lot.

Ganbatte! 🎉😀

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by yokaze** [comment]
It sounds nice to support Helm, PR is welcome 😊

**Comment by frederiko** [comment]
I would like to take a crack at it. I guess I can help with that if no one is on it.

**Comment by ymmt2005** [comment]
Thank you @frederiko !
To the best of my knowledge, I don't think anyone has touched it yet.

**Comment by kfirfer** [comment]
FYI
Im currently working on an helm chart for TopoLVM, when it will be ready enough , I will create a pull request, could take couple of days, will update

**Comment by frederiko** [comment]
@kfirfer Well, go ahead then. I was working on it too, but i guess you've already done something.

**Comment by briantopping** [comment]
@kfirfer @frederiko maybe if both of you have something, there would be benefits in comparing branches? No idea how far either of you are along, just floating ideas.

**Comment by kfirfer** [comment]
@frederiko @briantopping 
Hi
This is what Im working on (WIP):
https://github.com/kfirfer/topolvm/tree/helm-chart/deploy/chart/topolvm

If you could create a new branch called `helm-chart` or something like that, I could pull request it from the forked repo and working on that
Or else, you also could create new Repo calling "helm" or something like that under the project https://github.com/topolvm

**Comment by briantopping** [comment]
Many of the projects that I have seen which publish with Helm make a new project at the top level. I think it's a good idea.

**Comment by ymmt2005** [comment]
So, do you want a new repo?
I can create one for this!

**Comment by kfirfer** [comment]
@ymmt2005 
yes would be great

**Comment by ymmt2005** [comment]
@kfirfer Do you have a good name for the repo?

**Comment by kfirfer** [comment]
@ymmt2005 
Hmm I don't really knows
As @briantopping said most of the projects called their repo as "helm" or "chart" , So I think it is sufficient, otherwise you have another idea

**Comment by kfirfer** [comment]
@ymmt2005 
Great ! thanks
I will create a branch calling "0.0.1" and play with it
looking forward for some reviews

**Comment by kfirfer** [comment]
Push some Init chart:
https://github.com/topolvm/helm/tree/0.0.1/charts/topolvm

Would like to hear some thoughts/reviews:
https://github.com/topolvm/helm/issues/1

**Comment by frederiko** [comment]
Will take a look. Maybe open a PR as draft so we can comment on it.

**Comment by kfirfer** [comment]
@frederiko 
Made PR as draft:
https://github.com/topolvm/helm/pull/3

**Comment by ymmt2005** [comment]
The work is being done at https://github.com/topolvm/helm now.
