### ISSUE TITLE
lights out recovery

### ISSUE THREAD

**Issue by kfox1111** [topolvm/topolvm#198]
**Describe the bug**
There does not seem to be any documentation or design notes around how to perform a lights out recovery

**To Reproduce**
The scheduler is configured to contact the topolvm scheduler running on localhost when deployed with the daemonset.
When just brought up from lights out, the topolvm scheduler won't be running, so I think can't be scheduled?

I also think if you do a rolling upgrade of the daemonset, it will also fail to schedule as the pod must be deleted first, then a new one can't schedule.

**Expected behavior**
There needs to be a way to automatically recover from an outage and perform upgrades of the scheduler

**Workaround**
As a workaround, I think you can disable the extension, start things up, then re-enable it

**Comment by ymmt2005** [comment]
I don't think there is such a problem.

The extended scheduler (topolvm-scheduler) is hooked only for Pods having
`topolvm.cybozu.com/capacity` resource requests.
https://github.com/topolvm/topolvm/blob/master/deploy/scheduler-config/scheduler-policy.cfg#L13

That resource is only requested by Pods claiming TopoLVM volumes.
Other pods are not affected.

**Comment by kfox1111** [comment]
OH, that causes it to be called out only if the pod references that type of resource? Ok, cool. Then yeah, I think its just fine.
