### ISSUE TITLE
Error open etc/topolvm/lvmd.yaml

### ISSUE THREAD

**Issue by leoxhj** [topolvm/topolvm#201]
**Describe the bug**

Got error while execute lvmd even the lvmd.yaml file exists right under /etc/topolvm/

```bash
[root@k8s-master01 topolvm]# ll
total 4
-rw-r--r-- 1 root root 125 Sep 10 21:17 lvmd.yaml
[root@k8s-master01 topolvm]# pwd
/etc/topolvm
[root@k8s-master01 topolvm]# lvmd
Error: open etc/topolvm/lvmd.yaml: no such file or directory
open etc/topolvm/lvmd.yaml: no such file or directory
```

**Environments**
- Version: CentOS Linux release 7.8
- OS: CentOS

**Comment by ymmt2005** [comment]
@leoxhj Thank you for reporting the issue.
It is being fixed in #202 .
