### ISSUE TITLE
Inquiry for kustomization.yaml in base

### ISSUE THREAD

**Issue by leoxhj** [topolvm/topolvm#203]
**Describe the bug**
Not sure if it is issue in `kustomization.yaml` file which namespace: `topolvm-system` hasn't yet been created before referred in `mutatingwebhooks.yaml` file.

 
```yaml
resources:
....
  - mutatingwebhooks.yaml
  - namespace.yaml
...
```

**Comment by satoru-takeuchi** [comment]
It's no problem since `MutatingWebhookConfiguration` resource is a cluster resource.
