### ISSUE TITLE
propose lvmd feature to support striped logical volume

### ISSUE THREAD

**Issue by leoxhj** [topolvm/topolvm#207]
## What

For some user cases, they're willing to use striped logical volume instead of linear, for instance, elasticsearch uses for log/search purpose,
in this scenario, the performance will get upto N(disk numbers)*time boost than linear. normally there will be options passed to `lvcreate` as shown below:

```bash
#man lvcreate 
......
        -i|--stripes Number
        -I|--stripesize Size[k|UNIT]
......
```
so, It would be nice to introduce kinds of options for users who can specify.

## How

Describe how to address the issue.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by toshipp** [comment]
Thanks.
We internally consider a similar feature that specifies default stripping number of disks.
Would you tell me more detail you need?
e.g. Is our plan sufficient or not? Do you need both linear and stripping in same time?

**Comment by leoxhj** [comment]
so far, we don't have such scenario which need both linear and stripping,  so basically, to specify either linear or stripping with numbers of disks is sufficient.

**Comment by toshipp** [comment]
Thanks.
So, it is sufficient that LV type per storage class rather than per PVC.

**Comment by leoxhj** [comment]
Hello, @toshipp, not sure when this feature will be available and we're eager to test asap:), thanks in advanced.

**Comment by toshipp** [comment]
I'm sorry.
Currently, we have no resources to advance this feature.
I can't promise you a schedule.

**Comment by leoxhj** [comment]
Dear @toshipp, we're considering to implement this feature ourselves since we have dealine for our project by end of this month.
I'm look forward to hearing your implementation solution to suggest us how we can archive on this,  solution details like: 
* where we can specifies disk_numbers and stripped types, should we specifie during pvc claiming?
* which go files should we update, files to update for instance as below, but we should dig out more:
```shell
controller\logicalvolume_controller.go
# lvmd part
lvmd\proto\lvmd.pb.go
lvmd\device_class_manager.go
# node part
# api
api\v1\logicalvolume_types.go
......
```
Your suggestion would be much appreciated.

**Comment by leoxhj** [comment]
@toshipp I have immature houghts regarding to hack one file `lvmd\command\lvm.go` during deployment of lvmd.service by specifying `-i{num}`, and for each k8s work nodes we have to build a 'special' lvmd binary with `-i{num}` where num can be get from `vgs |grep vg00|awk 'print $2'`。  T_T

**Comment by toshipp** [comment]
Welcome to your contribution!

I think configurations related to striping is appropriate to place in `lvmd.yaml`.
In this case, all other components are not affected, and users could use striped volumes as well as normal one.

Would you submit a proposal document in `docs/proposals` for the feature before sending main PR?

**Comment by leoxhj** [comment]
@toshipp in our case, I implemented code as shown below:


```bash
# lvm\command\lvm.go
func (g *VolumeGroup) CreateVolume(name string, size uint64, tags []string) (*LogicalVolume, error) {

	out, err := exec.Command("/sbin/vgs", "VolGroup01", "--noheadings", "-o", "pv_count").Output()
	if err != nil {
		log.Info("Initialize PV Count error:", map[string]interface{}{
			"[err]": err,
		})
	}
	pvCount := strings.Replace(strings.Replace(string(out), " ", "", -1), "\n", "", -1)

	lvcreateArgs := []string{"-n", name, "-L", fmt.Sprintf("%vg", size>>30), "-W", "y", "-y", "-i", pvCount}
	for _, tag := range tags {
		lvcreateArgs = append(lvcreateArgs, "--addtag")
		lvcreateArgs = append(lvcreateArgs, tag)
	}
	lvcreateArgs = append(lvcreateArgs, g.Name())
	if err := CallLVM("lvcreate", lvcreateArgs...); err != nil {
		return nil, err
	}
	return g.FindVolume(name)
}
```

**Comment by llamerada-jp** [comment]
Hi @leoxhj 

I think it would be better to extend the DeviceClass to switch striping. 
For example:
- Add `Stripe uint` to [DeviceClass](https://github.com/topolvm/topolvm/blob/c73db1220c9285682c9ba3277774a3c0ed1f468c/lvmd/device_class_manager.go#L21) (default value is 0)
- Expand `CreateVolume` and add a parameter to pass stripe count from DeviceClass.
- Add `-i` option to `lvcreate` command if the stripe count is not 0.

That way, users will be able to configure the striping feature if necessary.

@ymmt2005 @zoetrope @toshipp 
If there is a better way, I would like to hear some opinions.

**Comment by leoxhj** [comment]
@llamerada-jp I agreed with your opinion and is was also my previous thought to specifies option in /etc/topolvm/lvmd.yaml, I will try to figure out and see if I can change this accordingly, so user can easily make the configuration.

**Comment by bells17** [comment]
Hi, I created a Pull Request for this issue based on the https://github.com/topolvm/topolvm/issues/207#issuecomment-714184206 comment:
https://github.com/topolvm/topolvm/pull/229
And I added a support stripesize option too.

**Comment by toshipp** [comment]
@leoxhj 
The feature is now implemented in the master branch. (thanks! @bells17)
It will ship on the next release.
