### ISSUE TITLE
The demonstration with kind fails to launch a cluster due to absence of the official Docker images

### ISSUE THREAD

**Issue by y-taka-23** [topolvm/topolvm#211]
**Describe the bug**

The example cannot launch a kind cluster. It's because the current `example/Makefile` specifies `KUBERNETES_VERSION=v1.18.9`, on the other hand, the kindest/node images are released only for v1.18.0, 2, 4, 6 and 8. 

https://hub.docker.com/r/kindest/node/tags?page=1&name=v1.18

**Environments**

Vagrant on OS X

**To Reproduce**
1. cd topolvm/example
2. vagrant up
3. vagrant ssh
4. cd /vagrant/example
5. make setup
6. make BACKING_STORE=/tmp run
7. aborted with the error:

```
kind create cluster --name=topolvm-example --config /tmp/topolvm-cluster.yaml --image kindest/node:v1.18.9
Creating cluster "topolvm-example" ...
 ✗ Ensuring node image (kindest/node:v1.18.9) 🖼
ERROR: failed to create cluster: failed to pull image "kindest/node:v1.18.9": command "docker pull kindest/node:v1.18.9" failed with error: exit status 1
Command Output: Error response from daemon: manifest for kindest/node:v1.18.9 not found: manifest unknown: manifest unknown
Makefile:54: recipe for target 'launch-kind' failed
```

**Comment by ymmt2005** [comment]
Thank you for reporting the issue.  Fixing in #212 .
