### ISSUE TITLE
LVM commands need an exclusive lock to avoid conflicts that causes lvmd run on the host Os

### ISSUE THREAD

**Issue by little-guy-lxr** [topolvm/topolvm#222]
## What

we could set lvm config file /etc/lvm/lvm.conf      locking_type=1  which use flocks on files in locking_dir (see below) to avoid conflicting LVM2 commands running concurrently on a single machine.

if we have setted , can I create pv/vg/lv using those devices in containers ?
## How

Describe how to address the issue.

**Comment by toshipp** [comment]
I have a question to clarify your problem.
Do you want to create LVM volumes in a container on top of a PV from topolvm?

**Comment by llamerada-jp** [comment]
@little-guy-lxr 
If you trying to run lvmd using the container, the following similar issue has already existed.
https://github.com/topolvm/topolvm/issues/195

**Comment by llamerada-jp** [comment]
resolved
