### ISSUE TITLE
scheduler extender convert to scheduler framework 

### ISSUE THREAD

**Issue by little-guy-lxr** [topolvm/topolvm#252]
As we know , kubernetes may deprecrate scheduler extender for which has some shotcommings and is unfriendly for user, so recommend topolvm could take kubernetes scheduler framework as new scheduler extension.

**Comment by ymmt2005** [comment]
We will replace the scheduler extender with Storage Capacity Tracking in #193.
With storage capacity tracking, we can implement an optimal volume scheduling with the standard scheduler.

**Comment by toshipp** [comment]
We have no plan to do this now.
