### ISSUE TITLE
Dropped btrfs support, why?

### ISSUE THREAD

**Issue by coolermister** [topolvm/topolvm#253]
In latest version of topolvm, btrfs support was dropped. But why? 
I can understand point of view that brtfs is unnecessary duplication of functionality of lvm, but btrfs much better works with millions of small files. xfs and ext4 have limitations in that use case, fixed block size of 4kb for example, that often is too bigger than files.
Which leads to waste of space, and slower io. Unfortunately i'm using minio, and minio creates million's of metafiles.
I've tried to find some issues about btrfs, for example problems in work, or something, i don't know.
But i haven't find anything about it(
So question is simple, why? Does topolvm have any mysterious annotation, that can provide custom block size? May be i'm blind, but i don't find it too(
And thank you guys for making great product!
Topolvm v0.7.0
K8s: 1.19
OS: ubuntu 18.04

**Comment by llamerada-jp** [comment]
Hi @coolermister ,

The reasons for removing btrfs from support are as follows:

1. It seems that it would need some work to support btrfs when supporting ubuntu 20.04.
2. We are going to support mount options using mount-utils. However, We are not sure if mount-utils is compatible with btrfs.

We might support btrfs if it is clear that mount-utils is compatible with btrfs by doing some experiments.

Ref. [mount-utils](https://github.com/kubernetes/mount-utils)

**Comment by coolermister** [comment]
Hi! Just confirming, that topolvm 0.6.0 works with 1.19 k8s and ubuntu 20.04) Any updates about mount-utils and so on?

**Comment by toshipp** [comment]
Supporting Ubuntu 20.04 mentioned by llamerada-jp means that it is used as a base image for topolvm, however, we confirmed that updating the base image introduces compatibility issues with older kernels, so we decided to use ubuntu 18.04 meanwhile.
Therefore, the first issue is not a problem now.
I checked mount-uitls a bit, it seems to be able to support btrfs, so we can support btrfs again.
BTW, it is an extra cost and we have no plan to use btrfs internally, so it is a lower priority.
If you wish to use btrfs, simply install the btrfs-tools package in the image, IMO.
I was wondering you could try it or send a PR?

**Comment by toshipp** [comment]
To support btrfs fully, we need to merge this; https://github.com/topolvm/topolvm/pull/356

**Comment by llamerada-jp** [comment]
I think we need an additional PR to use the btrfs command in containers; #357

**Comment by coolermister** [comment]
Thank you for your answers! Well, i will try to build lvmd and images with this two PR's, and test it. I will report here about how it works)

**Comment by coolermister** [comment]
Well, work's pretty well) Thank you, guys!
