### ISSUE TITLE
mkfs.xfs incompatibility whith RHEL/Centos7.X

### ISSUE THREAD

**Issue by SergeAlexandre** [topolvm/topolvm#257]
**Describe the bug**
On a Centos7.9 based kubernetes cluster, I was unable to create a pod with a topolvm based PVC with xfs file system.

**Environments**
- Version: 0.7.0
- OS: Centos7.9

**To Reproduce**
On a CentOS 7.9, when running a pod with a PVC on topolvm, I have the following error:
```
Events:
  Type     Reason                  Age                From                     Message
  ----     ------                  ----               ----                     -------
  Normal   Scheduled               <unknown>                                   Successfully assigned default/visitor to kspray1
  Normal   SuccessfulAttachVolume  52s                attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-de572ac9-12c2-4ee8-89ec-a46cb001d435"
  Warning  FailedMount             16s (x7 over 48s)  kubelet, kspray1         MountVolume.SetUp failed for volume "pvc-de572ac9-12c2-4ee8-89ec-a46cb001d435" : rpc error: code = Internal desc = mount failed: volume=a3c69f68-2e6d-4ce3-8dcc-0dcaf993f3b6, error=invalid argument
```

Digging a bit, it appears than the XFS file system created by the latest version of topolvm (based on ubuntu 20.04) is incompatible with an host on centOS 7.9 (and, I think older version).

- centos7.9 host mkfs.xfs **version: 4.5.0**
- ubuntu 20.04 (topolvm base image) **mkfs.xfs version: 5.3.0**

Digging a bit more, it appears that the latest version, by default, add some metadata (`rmapbt` and `reflink`) which break compatibility with older version. 

The good news is by switching these metadata off, the resulting filesystem is compatible with older xfs version

So, as a matter of proof, here is how I can temporary fix this, when there is a pod in the state described above:

```
# Log on the topolvm node
# kubectl -n topolvm-system exec -it node-dvcb6 -c topolvm-node  -- /bin/bash

# There is only on PV/PVC for this test. So here is the device uncorrectly formatted
# ls /dev/topolvm/
0d8a492d-7d34-4dc3-b020-76b3bad10eef

# Perform again mkfs.xfs with option to remove some metadata
mkfs.xfs -f -m rmapbt=0,reflink=0 /dev/topolvm/0d8a492d-7d34-4dc3-b020-76b3bad10eef
meta-data=/dev/topolvm/0d8a492d-7d34-4dc3-b020-76b3bad10eef isize=512    agcount=4, agsize=65536 blks
         =                       sectsz=512   attr=2, projid32bit=1
         =                       crc=1        finobt=1, sparse=1, rmapbt=0
         =                       reflink=0
data     =                       bsize=4096   blocks=262144, imaxpct=25
         =                       sunit=0      swidth=0 blks
naming   =version 2              bsize=4096   ascii-ci=0, ftype=1
log      =internal log           bsize=4096   blocks=2560, version=2
         =                       sectsz=512   sunit=0 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0

```

Then, on next retry, the volume is mounted and the requesting pod is launched successfully:

```
Events:
  Type     Reason                  Age                From                     Message
  ----     ------                  ----               ----                     -------
  Normal   Scheduled               <unknown>                                   Successfully assigned default/visitor to kspray1
  Normal   SuccessfulAttachVolume  20m                attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-763c78ba-2eb3-45d0-badc-b28d4b39d597"
  Warning  FailedMount             19m (x7 over 20m)  kubelet, kspray1         MountVolume.SetUp failed for volume "pvc-763c78ba-2eb3-45d0-badc-b28d4b39d597" : rpc error: code = Internal desc = mount failed: volume=0d8a492d-7d34-4dc3-b020-76b3bad10eef, error=invalid argument
  Normal   Pulling                 19m                kubelet, kspray1         Pulling image "centos"
  Normal   Pulled                  19m                kubelet, kspray1         Successfully pulled image "centos" in 1.4883742s
  Normal   Created                 19m                kubelet, kspray1         Created container visitor
  Normal   Started                 19m                kubelet, kspray1         Started container visitor

```

So, I suggest you add these options (`-m rmapbt=0,reflink=0`) in the mkfs.xfs performed by the topolvm dameonset.

(In the meantime, I will switch to ext4).

Best regards

**Expected behavior**
Able to create PVPVC on centos7 based kubernetes cluster

**Comment by ymmt2005** [comment]
@bells17 
Do you think #247 will resolve this?

**Comment by SergeAlexandre** [comment]
No, unfortunately , I don't think  #247 will resolve this. As this problem is related to the way the filesystem is formatted (mkfs), not the way it is mounted.
What will resolve this issue would be a way to support mkfs option.

**Comment by bells17** [comment]
I'm sorry I didn't notice immediately.

> Do you think #247 will resolve this?

I don't think #247 will resolve this too.
Because mount-util package can't specify any options of mkfs command from outside.
https://github.com/kubernetes/mount-utils/blob/970284d76518fe1d18ea8a6d9103e201dd7c8910/mount_linux.go#L398-L409

**Comment by ymmt2005** [comment]
@bells17 
So, #247 would make it impossible to fix this problem?
Currently, we can fix this because we run `mkfs.xfs` in our own code.

**Comment by bells17** [comment]
Um... probably we can fix this by manually calling `mkfs.xfs` before calling  `FormatAndMount.`
