### ISSUE TITLE
latest main branch make build failed because dependent lib change 

### ISSUE THREAD

**Issue by little-guy-lxr** [topolvm/topolvm#267]
unix lib has changed so build failed

mkdir -p build
go build -o build/hypertopolvm -ldflags "-X github.com/topolvm/topolvm.Version=devel" ./pkg/hypertopolvm
filesystem/util.go:84:20: undefined: unix.MS_LAZYTIME
filesystem/util.go:86:10: undefined: unix.MS_RDONLY
filesystem/util.go:91:10: undefined: unix.Mount
filesystem/util.go:115:31: undefined: unix.UMOUNT_NOFOLLOW
make: *** [build/hypertopolvm] Error 2

**Comment by toshipp** [comment]
@little-guy-lxr 
Would you tell me your environment such as OS, lib version, using compiler version, or etc?

**Comment by little-guy-lxr** [comment]
> @little-guy-lxr
> Would you tell me your environment such as OS, lib version, using compiler version, or etc?

OS : linux 
compile go version:  go1.15
dependent package : golang.org/x/sys v0.0.0-20210124154548-22da62e12c0c

**Comment by llamerada-jp** [comment]
We updated `filesystem/util.go` in the latest main branch this morning. Could you try building with the latest source?

**Comment by little-guy-lxr** [comment]
latest source also has some problem because unix package update.  

list below:

 driver/node.go         unix.Mkdev         sfs.Frsize

filesystem/resizefs.go.   mounter.GetDiskFormat

**Comment by ymmt2005** [comment]
We could not reproduce the issue.

The main branch no longer contains these symbols:
> filesystem/util.go:84:20: undefined: unix.MS_LAZYTIME

It seems that you are compiling old source code.

**Comment by little-guy-lxr** [comment]
> We could not reproduce the issue.
> 
> The main branch no longer contains these symbols:
> 
> > filesystem/util.go:84:20: undefined: unix.MS_LAZYTIME
> 
> It seems that you are compiling old source code


I confirm that the source code is up to date， can you confirm that the fix is merge to main branch

**Comment by ymmt2005** [comment]
This is the last CI run on the current main branch.  Succeeded.
https://github.com/topolvm/topolvm/runs/2035955742

and none of us maintainers have the compilation problem.

**Comment by little-guy-lxr** [comment]
> This is the last CI run on the current main branch. Succeeded.
> https://github.com/topolvm/topolvm/runs/2035955742
> 
> and none of us maintainers have the compilation problem.

please check pull request #272

**Comment by ymmt2005** [comment]
Reproduced with GOARCH=386 as follows:

```
$ GOARCH=386 go build ./pkg/topolvm-controller/
# github.com/topolvm/topolvm/driver
driver/node.go:453:33: invalid operation: int64(sfs.Blocks) * sfs.Frsize (mismatched types int64 and int32)
driver/node.go:454:43: invalid operation: int64(sfs.Blocks - sfs.Bfree) * sfs.Frsize (mismatched types int64 and int32)
driver/node.go:455:33: invalid operation: int64(sfs.Bavail) * sfs.Frsize (mismatched types int64 and int32)
```

**Comment by ymmt2005** [comment]
@little-guy-lxr 
I'm afraid that we cannot support your build environment.
Could you give us the output of `go env`?
