### ISSUE TITLE
mount fails for topolvm volume

### ISSUE THREAD

**Issue by jbenham** [topolvm/topolvm#274]
**Describe the bug**
Volumes created by topolvm are created, but fail to mount into the pods.

The pod has the following messages:
```
Events:
  Type     Reason                  Age    From                     Message
  ----     ------                  ----   ----                     -------
  Normal   Scheduled               2m43s  default-scheduler        Successfully assigned android-build/topolvm-echo-test-867799b4f9-tp2fc to rtos-k8-111-247.ghs.com
  Normal   SuccessfulAttachVolume  2m44s  attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-3cf2294f-81b9-4245-8ef8-5fa8643d2cc6"
  Warning  FailedMount             41s    kubelet                  Unable to attach or mount volumes: unmounted volumes=[testvol], unattached volumes=[testvol default-token-nn7bn]: timed out waiting for the condition
  Warning  FailedMount             36s    kubelet                  MountVolume.SetUp failed for volume "pvc-3cf2294f-81b9-4245-8ef8-5fa8643d2cc6" : rpc error: code = DeadlineExceeded desc = context deadline exceeded
```
Running `lvdisplay` on the host the pod is assigned to shows that a logical volume was created with the appropriate size.

**Environments**
- Version: v0.8.0 (same behavior on v0.7.0)
- OS: Host is Debian 10
  -  Linux *hostname*.example.com 4.19.0-11-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17) x86_64 GNU/Linux
- Kubernetes: Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

**To Reproduce**
1. Create  test.yaml:  
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: android-build
  name: test-lvm-pvc
spec:
  storageClassName: topolvm-provisioner
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: topolvm-echo-test
spec:
  replicas: 1
  selector:
    matchLabels:
      container: test-topolvm
  template:
    metadata:
      labels:
        container: test-topolvm
    spec:
      containers:
        - name: echoserv
          image: k8s.gcr.io/echoserver:1.4
          volumeMounts:
            - name: testvol
              mountPath: /test
      volumes:
        - name: testvol
          persistentVolumeClaim:
            claimName: test-lvm-pvc
```
2. kubectl apply -f test.yaml

**Expected behavior**
The volume should mound and the pod should become ready.

**Additional context**
The fsType in the StorageClass has been changed to "ext4".

"lvmd" is only running on some nodes in the cluster. The pod is getting assigned to a node with lvmd. The "node" DaemonSet was modified to only run on the nodes with lvmd installed.

If additional logs or information would help, please ask.

**Comment by jbenham** [comment]
I attached the log.  I didn't see an obvious errors, but I'm not sure what I should see either.

[topolvm-node.log](https://github.com/topolvm/topolvm/files/6119308/topolvm-node.log)

**Comment by ymmt2005** [comment]
Thanks.

@bells17 @toshipp @llamerada-jp 
It seems that `topolvm-node` could receive the request but failed to send back a response.

**Comment by llamerada-jp** [comment]
@jbenham 
We added outputting some logs for debugging in [`logs-for-debug`](https://github.com/topolvm/topolvm/tree/logs-for-debug) branch to trace process in more detail.
Could you apply the docker image for debugging and get logs from topolvm-node again?
You can build an image by `make image` command after pulling the branch.

**Comment by jbenham** [comment]
Here's a log with the extra information. I don't see anything about formatting the volume, which seems like something that should happen before it mounts... I do see messages about EvalSymlinks2, which got added on the logs-for-debug branch, so it looks like the build and deploy to cluster part worked at least.

[topolvm-node-debug.log](https://github.com/topolvm/topolvm/files/6125723/topolvm-node-debug.log)

**Comment by llamerada-jp** [comment]
@jbenham 
Thank you for your reply and a log.
We noticed that `NodeUnpublishVolume` RPC is not finished in your log. `NodePublishVolume` will be blocked until `NodeUnpublishVolume` finishes by the common mutex. We need to know why `NodeUnpublishVolume` is not completing. We added more log output on the same branch to investigate the reason. Could you replace the docker image and get logs from topolvm-node again? and could you check the status of the volume has been deleted using `df` or `lvs` command in the node?

// `lock mutex in NodeUnpublishVolume` keyword may be contained in the log if new docker image is deployed.

**Comment by jbenham** [comment]
@llamerada-jp 
Thank you for helping and the extra logging.  I have some more data and some interesting results.

It now appears to work on one node but not the other. Previously, the scheduler was always picking one of the nodes, "node2", but when I tried again, it picked "node1".  Here is the log of it successfully creating the pod and mounting the volume on node1:

[topolvm-node-debug-node1-0312-0013.log](https://github.com/topolvm/topolvm/files/6128535/topolvm-node-debug-node1-0312-0013.log)

I created a second PVC and deployment and then also spawned that.  It was assigned to node2 and fails the same way as before.  Here is the log of it failing.

[topolvm-node-debug-node2-0312-0018.log](https://github.com/topolvm/topolvm/files/6128536/topolvm-node-debug-node2-0312-0018.log)

And here is the output of "lvs" on node2:
```
lvs
  LV                                   VG          Attr       LSize Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  4c616557-4208-4c56-8e6c-2a70e82fc2d8 topolvm-ssd -wi-a----- 5.00g  
```

The command was run after the error occurred. If I delete the pvc, then `lvs` doesn't show any output.

**Comment by llamerada-jp** [comment]
@jbenham 
It looks like topolvm-node is freezing when topolvm-node try to access to `/var/lib/kubelet/pods/8e3e9972-002c-4af6-9617-c0fc8dd9e482/volumes/kubernetes.io~nfs/inv` from your log. This is my guess, is there an NFS mounted ?
Could you access `/var/lib/kubelet/pods/8e3e9972-002c-4af6-9617-c0fc8dd9e482/volumes/kubernetes.io~nfs/inv` and check if the file is normal? And would you give us the output of `cat /proc/mounts` in the node?

**Comment by llamerada-jp** [comment]
If your system is using NFS, could you turn off NFS once to isolate the cause? If there is `/var/lib/kubelet/pods/8e3e9972-002c-4af6-9617-c0fc8dd9e482/volumes/kubernetes.io~nfs/inv` still, topolvm-node may freeze again. So please unmount it manually and make sure it is not left in `/proc/mounts`.

**Comment by jbenham** [comment]
@llamerada-jp The good news is that pod had been orphaned, but there was a stale NFS mount hanging around. I unmounted it and after that was able to make a pvc with topolvm.

Attempts to access `/var/lib/kubelet/pods/8e3e9972-002c-4af6-9617-c0fc8dd9e482/volumes/kubernetes.io~nfs/inv` would hang, even from the shell.

Does topolvm have other issues with NFS? We plan to use the combination of the two.  Is it possible to skip over `*/volumes/kubernetes.io~nfs*`?

**Comment by llamerada-jp** [comment]
@jbenham 
I'm glad it was resolved.

We are planning to make a patch to skip unnecessary mount information in `/proc/mounts` using the filter. Could you provide the output of `cat /proc/mounts` when using NFS to make the patch?

**Comment by llamerada-jp** [comment]
>  Could you provide the output of cat /proc/mounts when using NFS to make the patch?
We confirmed `/proc/mounts` using NFS.

**Comment by jbenham** [comment]
@llamerada-jp Is this what you need:
```
hosta.example.com:/export /var/lib/kubelet/pods/c1e8d874-36b4-403d-bfdb-0658ecd23367/volumes/kubernetes.io~nfs/hosta-1 nfs4 rw,relatime,vers=4.2,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=192.168.1.249,local_lock=none,addr=192.168.2.1 0 0
```

or do you need the whole output.  FYI: I changed the hostnames and ip, but the format should be the same.

**Comment by toshipp** [comment]
@jbenham 
We think that the issue is resolved in the main branch (it will be released in the future).
If you try the branch and face the same error, please report it again.

**Comment by jbenham** [comment]
Thank you for all the help. If I see other issues, I'll let you know.
