### ISSUE TITLE
Behavior when a pvc is deleted ? 

### ISSUE THREAD

**Issue by ant31** [topolvm/topolvm#275]
## What

As I'm reading the documentation I'd like more detail about this:

> TopoLVM does not care about Retain reclaim policy because CSI volumes can be referenced only via PersistentVolumeClaims.

is the PV retained or deleted once the pvc deleted?

**Comment by ymmt2005** [comment]
It should depend on the reclaim policy of the StorageClass.

If it is `Retain`, the PV should be retained.

**Comment by ant31** [comment]
Ok Thank you !
