### ISSUE TITLE
xfs mount failed 

### ISSUE THREAD

**Issue by little-guy-lxr** [topolvm/topolvm#283]
**Describe the bug**

volume mount failed   

 kubectl describd pod 

  Warning  FailedMount             3s (x4 over 8s)  kubelet                  MountVolume.SetUp failed for volume "pvc-89c14e5b-a82f-4f16-8250-f8a2298c7bcb" : rpc error: code = Internal desc = mount failed: volume=d7baea10-7182-4a4f-865e-69010fe57d11, error=mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t xfs -o defaults /dev/topolvm/d7baea10-7182-4a4f-865e-69010fe57d11 /var/lib/kubelet/pods/2b4a6426-b43e-4798-a959-9274335e8a36/volumes/kubernetes.io~csi/pvc-89c14e5b-a82f-4f16-8250-f8a2298c7bcb/mount

[root@acp-node-1 lxr]# dmesg | tail
[2936366.942347] IPVS: __ip_vs_del_service: enter
[2936368.664178] XFS (dm-2): Superblock has unknown read-only compatible features (0x4) enabled.
[2936368.667315] XFS (dm-2): Attempted to mount read-only compatible filesystem read-write.
[2936368.667317] XFS (dm-2): Filesystem can only be safely mounted read only.
[2936368.667359] XFS (dm-2): SB validate failed with error -22.
[2936666.002867] XFS (dm-2): Superblock has unknown read-only compatible features (0x4) enabled.
[2936666.005687] XFS (dm-2): Attempted to mount read-only compatible filesystem read-write.
[2936666.005690] XFS (dm-2): Filesystem can only be safely mounted read only.
[2936666.007457] XFS (dm-2): SB validate failed with error -22.
[2936667.236680] IPVS: __ip_vs_del_service: enter

[root@acp-slave debug]# lvm lvdisplay /dev/test/d7baea10-7182-4a4f-865e-69010fe57d11
  --- Logical volume ---
  LV Path                /dev/test/d7baea10-7182-4a4f-865e-69010fe57d11
  LV Name                d7baea10-7182-4a4f-865e-69010fe57d11
  VG Name                test
  LV UUID                eAefAX-592I-MOxQ-0Mnq-MBVV-eby0-viwQJF
  LV Write Access        read/write
  LV Creation host, time acp-slave, 2021-03-24 14:47:02 +0800
  LV Status              available
  LV Size                1.00 GiB
  Current LE             256
  Segments               1
  Allocation             inherit
  Read ahead sectors     auto
  - currently set to     8192
  Block device           253:2

**Environments**

k8s: 1.19
system: centos7
node xfs version: v5
storageClass fstype: xfs

**To Reproduce**
 
make storageclass fs type xfs

**Expected behavior**

**Additional context**

**Comment by toshipp** [comment]
@little-guy-lxr 
Would you tell me your kernel version?
We already know that xfs with kernel v4.8 or earlier causes a problem.
https://github.com/topolvm/topolvm#supported-environments

**Comment by little-guy-lxr** [comment]
> @little-guy-lxr
> Would you tell me your kernel version?
> We already know that xfs with kernel v4.8 or earlier causes a problem.
> https://github.com/topolvm/topolvm#supported-environments

kernel :3.10

but xfs version is 5 and has xfsprogs 4.5 installed , In theory, should not mount failed， so i turn off the reflink , then mount successful ,  please check pr  #284

**Comment by toshipp** [comment]
Thank you for your information.
It is similar to #257.
TopoLVM uses xfsprogs in its container image, host installed one is not used.
The reason for the issue is the difference between the host kernel xfs version and the kernel xfs version.
I recommend updating your kernel.
