### ISSUE TITLE
Replace some manifests in test with embed.

### ISSUE THREAD

**Issue by llamerada-jp** [topolvm/topolvm#286]
## What

There are some manifest strings in source code.
We want replace those strings using [embed](https://golang.org/pkg/embed/).

## How

Replace some manifest strings in source code using [embed](https://golang.org/pkg/embed/).

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by toshipp** [comment]
closed via #288
