### ISSUE TITLE
add app.kubernetes.io/created-by:topolvm label to LogicalVolume resource

### ISSUE THREAD

**Issue by llamerada-jp** [topolvm/topolvm#300]
## What

- Add `app.kubernetes.io/created-by:topolvm` label to LogicalVolume resource.
- ` app.kubernetes.io/created-by` is a recommended label to describe what controller creates the resource.
  ref. https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels

## How

- Add the label when create LogicalVolume resource.
- Check and add the label if it isn't exist when update LogicalVolume resource.
 
## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by toshipp** [comment]
`app.kubernetes.io/created-by` refers to the controller name, so it would be better to set the label value to `topolvm-controller`.

**Comment by bells17** [comment]
Should add `app.kubernetes.io/managed-by: topolvm-controller` label too?

**Comment by bells17** [comment]
> Add the label when create LogicalVolume resource.
> Check and add the label if it isn't exist when update LogicalVolume resource.

I think these will be possible by only implementing label addition processing in the logicalvolume controller.

**Comment by toshipp** [comment]
> Should add app.kubernetes.io/managed-by: topolvm-controller label too?
No, `app.kubernetes.io/managed-by` label indicates not a controller but a tool (something like as helm).

**Comment by toshipp** [comment]
>I think these will be possible by only implementing label addition processing in the logicalvolume controller.

Absolutely. We implement the logic in the controller.

**Comment by bells17** [comment]
> No, app.kubernetes.io/managed-by label indicates not a controller but a tool (something like as helm).

I see. Thank you.
