### ISSUE TITLE
DaemonSet lvmd manifest does not work by default

### ISSUE THREAD

**Issue by inductor** [topolvm/topolvm#328]
**Describe the bug**

I think it's either container registry or yaml file provided is incorrect.

https://github.com/topolvm/topolvm/blob/main/deploy/manifests/lvmd/lvmd.yaml#L75

```
  Warning  ErrImageNeverPull  6s (x3 over 20s)  kubelet            Container image "quay.io/topolvm/topolvm-with-sidecar:latest" is not present with pull policy of Never
  Warning  Failed             6s (x3 over 20s)  kubelet            Error: ErrImageNeverPull
```

**Environments**
- Version:
- OS:

**To Reproduce**

**Expected behavior**
DaemonSet has to be deployed successfully 

**Additional context**

**Comment by toshipp** [comment]
We use the manifest in a test environment only, so I miss specifying the image version.
We are now migrating a deployment tool from kustomize to helm, the issue will be resolved.
