### ISSUE TITLE
helm repo failed to fetch

### ISSUE THREAD

**Issue by zhuozl** [topolvm/topolvm#331]
**Describe the bug**

helm repo add topolvm https://topolvm.github.io/topolvm

Error: looks like "https://topolvm.github.io/topolvm" is not a valid chart repository or cannot be reached: failed to fetch https://topolvm.github.io/topolvm/index.yaml : 404 Not Found

**Environments**
- Version:
- OS:
CentOS Linux release 7.6.1810 (Core) 

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by toshipp** [comment]
We have not released helm yet.

**Comment by toshipp** [comment]
It can be downloaded now.
