### ISSUE TITLE
artifacthub

### ISSUE THREAD

**Issue by kfox1111** [topolvm/topolvm#368]
The helm repo should be added to artifacthub.io so that it can more easily be found.

**Comment by HaveFun83** [comment]
@satoru-takeuchi any news here?

**Comment by satoru-takeuchi** [comment]
@HaveFun83 No progress on this. We are working on #168 which changes the domain name of topolvm-related labels, attributes, and so on. We'd like to publish TopoLVM to artifacthub after that to minimize the effect of the domain name change.

**Comment by toshipp** [comment]
we now serve it here: https://artifacthub.io/packages/helm/topolvm/topolvm
