### ISSUE TITLE
Avoid getting incorrect information from `/proc/mounts`.

### ISSUE THREAD

**Issue by llamerada-jp** [topolvm/topolvm#371]
## What

We rarely get wrong information from `/proc/mounts` if read it simply according to the following post.
ref. https://github.com/kubernetes/kubernetes/issues/31272#issuecomment-300209720

## How

Read and parse `/proc/mounts` repeatedly until we get 2 in a row that match.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by manugupt1** [comment]
Hi, I think this is already implemented: 

https://github.com/kubernetes/utils/blob/master/io/read.go#L43-L63

I am trying to figure out do you think, if there are missing places?

**Comment by llamerada-jp** [comment]
@manugupt1 

Thank you for the useful information🤗
