### ISSUE TITLE
lvmd did not create lvmd.socket.

### ISSUE THREAD

**Issue by cupnes** [topolvm/topolvm#375]
**Describe the bug**
lvmd sometimes stopped responding to communications from gRPC.

**Environments**
- Version: 0.10.0

**Expected behavior**
lvmd responds to communication from gRPC.

**Comment by toshipp** [comment]
#374 is intended to mitigate this.

**Comment by llamerada-jp** [comment]
#374 is not related this issue.

**Comment by toshipp** [comment]
Though I can not reproduce this issue, It happened. One possible solution is to add livenessProbe to confirm lvmd is working.
Recent k8s provides a gRPC probe feature.
https://kubernetes.io/blog/2022/05/13/grpc-probes-now-in-beta/
(for older k8s, it is better to add a subcommand to check the RPC into lvmd and use it by exec probe.)

**Comment by toshipp** [comment]
Unfortunately, we use an unix domain socket for lvmd gRPC, so we can not use k8s probe...

**Comment by cupnes** [comment]
Bug fix policy:
1. Implement a mechanism ([GRPC Health Checking Protocol](https://github.com/grpc/grpc/blob/master/doc/health-checking.md)) in lvmd to accept Health Check via gRPC.
2. Configure the pod to automatically restart if this Health Check fails.
