### ISSUE TITLE
Support for disabling pvc auto removal

### ISSUE THREAD

**Issue by mape90** [topolvm/topolvm#397]
**What should the feature do:**
There should be option to disable PVC deletion when node is deleted.

**What is use case behind this feature:**
Certain K8s cluster use node replacement strategy for node upgrades. (CAPI does this) In those cases node is temporary removed from cluster and rebuild. After that it joins back to the cluster. Node name will be same and all data disks will be kept intact. 
So once the node joins back to the cluster it would behave similarly as in case of node reboot. For point of view of Topolvm.

This could also be used in cases where host operating system needs to be reinstalled, but data disks would like to be reused with their data. So that expensive data migration would not be needed.

**Comment by llamerada-jp** [comment]
Hi, @mape90 
Thanks for your issue. I think your request is appropriate.
I have a question to consider the specification. Could you please tell me how can we confirm which node is updating or retired, if you know?

**Comment by mape90** [comment]
Hi @llamerada-jp,

There is no way to differentiate between those cases as the information might not even be present in k8s cluster in any form. For that reason this request is to have way to disable it totally. So when auto removal is disabled it would move the responsibility of removal from topoLVM to cluster admin.

This would also make it simpler for topoLVM to implement as it would be just single flag to enable or disable this. So there do not need to be any special labels, timers or checks to be done by topoLVM.

**Comment by llamerada-jp** [comment]
@mape90 

The following changes seem to be necessary to implement this feature.

- Add a new option to topolvm-controller to disable NodeReconciler and also changes helm chart to use this option.
- Add a new test case of this option in `cleanup_test.go` and change the test matrics in Github Actions to call the new test.
- Update document.

It would be great if you create a PR, is it possible?

**Comment by macaptain** [comment]
Hi there. I'm new to the TopoLVM project but I'd be happy to try implementing this according to your suggestions @llamerada-jp. Feel free to assign the issue to me.

**Comment by llamerada-jp** [comment]
@macaptain 
Thank you for your offer. I wonder if you could implement this issue. Would you look at the program first and ask questions if you don't understand something.
