### ISSUE TITLE
Metrics for managed PV and LV

### ISSUE THREAD

**Issue by DebakelOrakel** [topolvm/topolvm#401]
**What should the feature do:**
Metrics for:
* Nr. of TopoLVM managed pv
* Nr. of LogicalVolumes

**What is use case behind this feature:**
If the retention policy is `Retain` and a user deletes a pvc/pv the corresponding LogicalVolume is not deleted, this way we can detect lingering LVs on the cluster.

**Comment by toshipp** [comment]
Good. If you submit a PR, we are happy to review it.
