### ISSUE TITLE
Proposal: dedicated disks and allocation policy

### ISSUE THREAD

**Issue by lentzi90** [topolvm/topolvm#415]
**What should the feature do:**

It should be possible to ask for dedicated disks for performance sensitive applications that benefit from "owning" the whole disk they use. A "softer" variant of this is also of interest: basically setting the `--alloc` flag to `contiguous` or `cling` in order to keep the data on a single PV. In this case the PV can still be shared with other applications.

I have a proposal ready and will create a PR for it soon so we can discuss it.

**What is use case behind this feature:**

We have a use case where we want dedicated disks for certain applications (e.g. ceph). The idea is that these applications should not share the PV/disk with other for performance reasons.
In some cases it may be too expensive to allocate the whole disk for a single application. But it would still be beneficial to pick the allocation policy (e.g. set it to `contiguous`).

**Comment by satoru-takeuchi** [comment]
We decided to add a dedicated disk feature. The remaining feature will be discussed in #420.

**Comment by toshipp** [comment]
closed via #420
