### ISSUE TITLE
Unit tests that require root are skipped

### ISSUE THREAD

**Issue by lentzi90** [topolvm/topolvm#438]
**Describe the bug**
Unit tests that require root are skipped. I think they are never run.

**To Reproduce**
1. On any PR, check the "Main / build (pull_request)"
2. Check what tests are skipped in "Run make test" and "Run sudo -E env..."
3. Both these skip some tests:
   ```
   === RUN   TestLVService
    lvservice_test.go:18: run as root
   --- SKIP: TestLVService (0.00s)
   === RUN   TestVGService
    vgservice_test.go:205: run as root
   --- SKIP: TestVGService (0.00s)
   ```

**Expected behavior**
The tests should run at least once.

**Additional context**
Check the run here for example: https://github.com/topolvm/topolvm/runs/5109171807?check_suite_focus=true

**Comment by bells17** [comment]
https://github.com/bells17/tmp/runs/5992860232

https://github.com/bells17/tmp/blob/4707c18abe30a28d465ec6ffd8c2c5bfa051d36f/.github/workflows/main.yaml
https://github.com/bells17/tmp/blob/4707c18abe30a28d465ec6ffd8c2c5bfa051d36f/main.go
https://github.com/bells17/tmp/blob/4707c18abe30a28d465ec6ffd8c2c5bfa051d36f/main_test.go
