### ISSUE TITLE
Use ghcr.io for conatiner registry

### ISSUE THREAD

**Issue by toshipp** [topolvm/topolvm#455]
## What

We now use quay.io for container registry, but it is boring to manage users and credentials.
Github provides a container registry service. It is free for public images and its access control is integrated with GitHub.

## How

- enable github container registry
- migrate all images from quay.io to ghcr.io
- rewrite image names on codes.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by bells17** [comment]
ghcr.io: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry
