### ISSUE TITLE
Add a delete protection for LogicalVolume CRs

### ISSUE THREAD

**Issue by machine424** [topolvm/topolvm#492]
Hello,

**What should the feature do:**

Avoid garbage collecting the underlying logical volume if a `LogicalVolume` CR does not have an annotation when being deleted. As proposed by postgres-operator: https://github.com/zalando/postgres-operator/blob/7c878f8aaab9bee1f86f2022fa89705c53da77e0/docs/administrator.md#delete-protection-via-annotations

I couldn't find any equivalent mechanism proposed by topolvm

**What is use case behind this feature:**

Even with a good management of RBAC + backups and data duplication, mistakes could still happen, it'd be appreciated to have a safeguard.

- Protect against accidental deletion of  the `LogicalVolume ` CRD (Kubernetes would delete the CR, but we'll keep the data)
- Safer and less stressful.

**Comment by cupnes** [comment]
I don't think it is necessary to implement this as a topolvm feature. For example, how about using Open Policy Agent?
https://www.openpolicyagent.org/docs/latest/kubernetes-tutorial/

**Comment by machine424** [comment]
Hello,

I'm sorry, but we do not use OPA and we do not want to rely on a mutating webhook for this (no problem if topolvm's mutations webhooks are bypassed, at worst the Pod will not be created, but we'll not lose all the data). The mutating webhook may fail or get bypassed.

I think this is a POF that must be dealt with at topolvm level. I even think that this should be a kubebuilder feature.

We can help with the implementation if needed.

**Comment by cupnes** [comment]
From my understanding, in the case of postgres-operator' delete protection, you can DELETE but you can undo it from the log. It seems not a good idea to me because an actual volume remains without its corresponding metadata, which makes the reconciler much more complicated. Also, it is preferable for me to prevent accidental volume deletion itself rather than recovering after deletion. I understand you were worried about RBAC being misconfigured, but I still think it is a good idea to use the RBAC properly.

**Comment by machine424** [comment]
Hello @cupnes,


> From my understanding, in the case of postgres-operator' delete protection, you can DELETE but you can undo it from the log. It seems not a good idea to me because an actual volume remains without its corresponding metadata, which makes the reconciler much more complicated.

postgres-operator will ignore the DELETE of a CR if it does not have the appropriate annotations. We just need to recreate the deleted CR and the controller will sync, then you just need to add the appropriate annotations and delete the CR if you wan the controller to do the cleaning.

> Also, it is preferable for me to prevent accidental volume deletion itself rather than recovering after deletion. 

I propose a delete protection, so there will no deletion to recover from ;) Also, we cannot prevent all accidents, the err is human and safeguards are really needed.

> I understand you were worried about RBAC being misconfigured, but I still think it is a good idea to use the RBAC properly.

Not really :) I even think we have too strict RBAC  ;). I was talking about the OPA webhook, I said it may be bypassed. But even with properly set up RBAC, we can still delete a CR or CRD by mistake.

**Comment by cupnes** [comment]
@machine424 I'm sorry. We have no plans to implement this feature. Please contact kubebuilder or others.

**Comment by machine424** [comment]
Hello @cupnes,

Could you please share the reasons?

We can help with the implementation and I don't think it'll be something hard to maintain.

This is really critical, this is a real eligible feature. We're not even sure all Topolvm users are aware of this.

**Comment by cupnes** [comment]
@machine424 
Once again, I will respond to your earlier comments.

> I'm sorry, but we do not use OPA and we do not want to rely on a mutating webhook for this (no problem if topolvm's mutations webhooks are bypassed, at worst the Pod will not be created, but we'll not lose all the data). The mutating webhook may fail or get bypassed.

This is not the case because admission webhooks can be configured so that they cannot be bypassed even if the webhook server is down. It is possible to control this with a validation webhook.

**Comment by machine424** [comment]
Hello @cupnes,

Yes, I am aware of the failure policy, but these webhooks may get unregistered (ValidatingWebhookConfiguration deleted or misconfigured) by mistake or for any other reason. You don't want to rely on a third party to avoid this crucial POF.

**Comment by cupnes** [comment]
@machine424 
I think this kind of protection against accidental deletion should be implemented in general. The following KEP discusses protection as a generic feature of Kubernetes. Why don't you join this discussion?
https://github.com/kubernetes/enhancements/issues/2839

**Comment by machine424** [comment]
Hello @cupnes,

Cool, thank you for the link, I'll watch it and see what I can do to help. This shows that deletion protection is a big deal not only to us :)

We know that it'll take months or even years until the KEP graduates to GA. I know I could be stubborn but we would like to run Topolvm in production ASAP and I was wondering if Topolvm can handle the case when the CRD is deleted.

before triggering the volume deletion, it can try to retrieve the corresponding `LogicalVolume`, if the API responds with an `unknown type`, this means the CRD was deleted and we can skip the volume deletion. (I see the node component is meant talk to the kube API and can thus make this check)

It can be put behind a flag (as we do for `--skip-node-finalize` e.g.).

**Comment by cupnes** [comment]
@machine424 I understand that you have an implementation plan. But again, I think such prevention of accidental deletion should be implemented in general.
