### ISSUE TITLE
Add CRD fields to know when was the last time the Volume got mounted/unmounted

### ISSUE THREAD

**Issue by maxime1907** [topolvm/topolvm#503]
**What should the feature do:**

Expose fields into the CRD LogicalVolume to know when was the last time that the PersistentVolume was mounted/unmounted
Everyone is already doing it like for instance [OpenStack Cinder Volume](https://github.com/openstack/python-cinderclient/blob/d1853510c005125d112da87374df7a9a6f1a1ebf/cinderclient/tests/unit/v3/fakes_base.py#L45), [GKE Disk Volume](https://cloud.google.com/compute/docs/reference/rest/v1/disks#resource:-disk)...

So I was thinking to implement it the google way:
```
"lastAttachTimestamp": string,
"lastDetachTimestamp": string,
```

**What is use case behind this feature:**

Know when we last used a specific LogicalVolume so that we can clean up clusters volumes in accordance with the company retention policy and teams management of their data.

PS: If this feature request is accepted, i will code it and open a PR on this repository.

**Comment by daichimukai** [comment]
IMHO, it is better to use annotation for these timestamps since these are not necessary for TopoLVM to work. LogicalVolume CR is a resource that only topolvm-controller cares about, so annotation to PVC might be more appropriate.

PVCs can be mounted by multiple Pods at the same time, so even if the lastDetachTimestamp is later than the lastAttachTimestamp, some pod may mounted the PVC. It seems undesirable behavior to me.

**Comment by maxime1907** [comment]
Okay i see so is it better for you if we just annotate a field last_updated to the PVCs created by TopoLVM ?

**Comment by daichimukai** [comment]
TopoLVM does not create PVCs. 

To track mount/unmount time of PVCs, one possible solution is to make topolvm leave Kubernetes event when the PVC is mounted or unmounted. I think this is better than annotation.
Another idea is to use metrics: some of kubelet's PVC metrics (e.g. `kubelet_volume_stats_capacity_bytes`) are exported only when the PVC is mounted by at least one Pod. This can be used to determine when it was last mounted.

**Comment by maxime1907** [comment]
Okay I understand your point of view and I just wanted to say that Kubernetes events are meant for audit purposes and not as some sort of history.

As for the metrics idea, it would mean that we would have to be dependent on two solutions: TopoLVM and the prometheus stack.

I really think that adding a simple annotation to LogicalVolumes CRs like OpenStack and Google does for their volumes/disks management should be the way to go.

**Comment by daichimukai** [comment]
> I just wanted to say that Kubernetes events are meant for audit purposes and not as some sort of history.

I've never heard of that. Could you give me a link to your source of information?

> I really think that adding a simple annotation to LogicalVolumes CRs like OpenStack and Google does for their volumes/disks management should be the way to go.

I'm not familiar with OpenStack or GCE, so I don't know how far I can refer to them. TopoLVM is software for Kuberenetes, so I would like to follow the practices at Kuberentes. I think for now using Kubernetes events or Prometheus metrics is more convenient approach.
