### ISSUE TITLE
Support 'inline' CSI - Ephemeral volumes?

### ISSUE THREAD

**Issue by scott-dunt** [topolvm/topolvm#541]
According to  https://github.com/topolvm/topolvm/issues/75#issuecomment-579887435  should the topolvm.cybozu.com driver be tagged with volumeLifecycleModes = Ephemeral or not?

I can create - use access TopoLVM if I create a PVC in K8s (v1.24.3)  but if I attempt to use Ephemeral support K8s either ignores TopoLVM and attempts to create the Ephemeral volume on the local host drive itself and NOT on the LVM partition.  (Topolvm is the ONLY and marked as default storage driver)
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: topolvm-provisioner
  uid: 1d0eddde-88cd-46fe-abb2-4b180d359922
  resourceVersion: '209895'
  creationTimestamp: '2022-07-20T16:06:03Z'
  labels:
    app.kubernetes.io/instance: topolvm
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: topolvm
    app.kubernetes.io/version: 0.14.1
    helm.sh/chart: topolvm-8.0.1
  annotations:
    meta.helm.sh/release-name: topolvm
    meta.helm.sh/release-namespace: topolvm-system
    storageclass.kubernetes.io/is-default-class: 'true'
  managedFields:
    - manager: helm
      operation: Update
      apiVersion: storage.k8s.io/v1
      time: '2022-07-20T16:06:03Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:allowVolumeExpansion: {}
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
            f:storageclass.kubernetes.io/is-default-class: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
        f:parameters:
          .: {}
          f:csi.storage.k8s.io/fstype: {}
        f:provisioner: {}
        f:reclaimPolicy: {}
        f:volumeBindingMode: {}
  selfLink: /apis/storage.k8s.io/v1/storageclasses/topolvm-provisioner
provisioner: topolvm.cybozu.com
parameters:
  csi.storage.k8s.io/fstype: xfs
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
```

Or if I attempt to call the csi driver, I get "MountVolume.NewMounter initialization failed for volume "csi-volume" : volume mode "Ephemeral" not supported by driver topolvm.cybozu.com (only supports ["Persistent"])"  which leads me back to should the driver be labeled Ephemeral  and if so.. How do I update that, since K8s says its immutable?

Thanks

**Comment by toshipp** [comment]
we dropped to support inline ephemeral volume. see https://github.com/topolvm/topolvm/blob/main/CHANGELOG.md#changed
Please use generic ephemeral volume instead if you want to use ephemeral volume.
https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#generic-ephemeral-volumes
