### ISSUE TITLE
lvmd pod can't start

### ISSUE THREAD

**Issue by alanyanglong** [topolvm/topolvm#559]
2022-09-02T02:41:16.344639Z topolvm-lvmd-0-m85zp lvmd info: "configuration file loaded: " device_classes="[0xc00034fc00]" file_name="/etc/topolvm/lvmd.yaml" socket_name="/run/topolvm/lvmd.sock"

2022-09-02T02:41:16.370328Z topolvm-lvmd-0-m85zp lvmd error: "Error while retrieving volume groups"
Error: strconv.ParseUint: parsing "-1": invalid syntax

strconv.ParseUint: parsing "-1": invalid syntax

What's the issue? and How to fix it ?    Thanks

**Comment by llamerada-jp** [comment]
According to your message, lvmd.yaml containing an wrong configuration value. It seems to be set to -1 where it should be a positive integer.

**Comment by alanyanglong** [comment]
> According to your message, lvmd.yaml containing an wrong configuration value. It seems to be set to -1 where it should be a positive integer.

root@topolvm-lvmd-0-6sfbx:/# /lvmd --container
2022-09-02T09:29:13.435193Z topolvm-lvmd-0-6sfbx lvmd info: "configuration file loaded: " device_classes="[0xc000125f00]" file_name="/etc/topolvm/lvmd.yaml" socket_name="/run/topolvm/lvmd.sock"
2022-09-02T09:29:13.464737Z topolvm-lvmd-0-6sfbx lvmd error: "Error while retrieving volume groups"
Error: strconv.ParseUint: parsing "-1": invalid syntax
strconv.ParseUint: parsing "-1": invalid syntax
root@topolvm-lvmd-0-6sfbx:/# cat /etc/topolvm/lvmd.yaml
socket-name: /run/topolvm/lvmd.sock
device-classes: 
  - default: true
    name: ssd
    spare-gb: 10
    volume-group: vg1

**Comment by daichimukai** [comment]
I suspect that the output of lvm command is not what lvmd expect. Could you share the output of the following command?
```
sudo lvm fullreport --config 'report {output_format=json pvs_cols_full="pv_name" segs_cols_full="lv_uuid" pvsegs_cols_full="lv_uuid"} global {units=b suffix=0}' --configreport pv -o-pv_name --configreport seg -o-lv_uuid --configreport pvseg -o-lv_uuid --configreport vg -o vg_name,vg_uuid,vg_size,vg_free --configreport lv -o lv_uuid,lv_name,lv_full_name,lv_path,lv_size,lv_kernel_major,lv_kernel_minor,origin,origin_size,pool_lv,lv_tags,lv_attr,vg_name,data_percent,metadata_percent,pool_lv
```

**Comment by alanyanglong** [comment]
> sudo lvm fullreport --config 'report {output_format=json pvs_cols_full="pv_name" segs_cols_full="lv_uuid" pvsegs_cols_full="lv_uuid"} global {units=b suffix=0}' --configreport pv -o-pv_name --configreport seg -o-lv_uuid --configreport pvseg -o-lv_uuid --configreport vg -o vg_name,vg_uuid,vg_size,vg_free --configreport lv -o lv_uuid,lv_name,lv_full_name,lv_path,lv_size,lv_kernel_major,lv_kernel_minor,origin,origin_size,pool_lv,lv_tags,lv_attr,vg_name,data_percent,metadata_percent,pool_lv

 {
      "report": [
          {
              "vg": [
                  {"vg_name":"vg2", "vg_uuid":"sJuNAj-dhpd-9x6n-VrGr-Me5n-r963-XeIFQr", "vg_size":"21458059264", "vg_free":"10687086592"}
              ]
              ,
              "pv": [
                  {}
              ]
              ,
              "lv": [
                  {"lv_uuid":"6OawEU-iED9-YhD3-lO0z-RSZz-Eqzv-FBZs8a", "lv_name":"pool2", "lv_full_name":"vg2/pool2", "lv_path":"", "lv_size":"10737418240", "lv_kernel_major":"-1", "lv_kernel_minor":"-1", "origin":"", "origin_size":"", "pool_lv":"", "lv_tags":"", "lv_attr":"twi---tz--", "vg_name":"vg2", "data_percent":"", "metadata_percent":"", "pool_lv":""}
              ]
              ,
              "pvseg": [
                  {},
                  {},
                  {},
                  {}
              ]
              ,
              "seg": [
                  {}
              ]
          }
          ,
          {
              "vg": [
                  {"vg_name":"ubuntu-vg", "vg_uuid":"ChqHRk-oIrB-t46v-W8vM-XpsR-2a3R-1hIwY9", "vg_size":"20396900352", "vg_free":"0"}
              ]
              ,
              "pv": [
                  {}
              ]
              ,
              "lv": [
                  {"lv_uuid":"7GTNeS-LEwJ-a7Zk-sNRr-lYnu-Tv4u-ahDPVM", "lv_name":"ubuntu-lv", "lv_full_name":"ubuntu-vg/ubuntu-lv", "lv_path":"/dev/ubuntu-vg/ubuntu-lv", "lv_size":"20396900352", "lv_kernel_major":"253", "lv_kernel_minor":"0", "origin":"", "origin_size":"", "pool_lv":"", "lv_tags":"", "lv_attr":"-wi-ao----", "vg_name":"ubuntu-vg", "data_percent":"", "metadata_percent":"", "pool_lv":""}
              ]
              ,
              "pvseg": [
                  {}
              ]
              ,
              "seg": [
                  {}
              ]
          }
          ,
          {
              "vg": [
                  {"vg_name":"vg1", "vg_uuid":"KyAxBI-4Zw1-RqC0-9Qcb-22ct-wcL1-guVK4y", "vg_size":"21458059264", "vg_free":"21458059264"}
              ]
              ,
              "pv": [
                  {}
              ]
              ,
              "lv": [
              ]
              ,
              "pvseg": [
                  {}
              ]
              ,
              "seg": [
              ]
          }
      ]
  }

Thanks!

**Comment by daichimukai** [comment]
> "lv_kernel_major":"-1", "lv_kernel_minor":"-1"

lvmd expects that these are non-negative integers. It might cause the crash.
I am not sure, but it may be due to the fact that the LV `vg2/pool2` is not activated.
Could you try activating it and check if lvmd works?

**Comment by nbalacha** [comment]
The same issue is seen when a snapshot is created - since it is not activated by default, the Major and Minor numbers are set to -1.
This was introduced in https://github.com/topolvm/topolvm/pull/501 and the failure is in :
https://github.com/topolvm/topolvm/blob/f18dde4f5ff96efe78350ab58f68f8583ccc361d/lvmd/command/lvm_json.go#L99
https://github.com/topolvm/topolvm/blob/f18dde4f5ff96efe78350ab58f68f8583ccc361d/lvmd/command/lvm_json.go#L103

This affects the thin snapshot implementation in topolvm. Creating a volumesnapshot fails and the snapshot never becomes ready to use. If there is a volume that is not activated, lvmd container will keep crashing on startup.

What is the best way to fix this? @daichimukai

**Comment by tasleson** [comment]
> Can we remove the error check for now in order to allow this to work?

When the conversion fails, the `strconv.ParseUnit` will return 0.  This must be an acceptable value for the rest of topolvm, so we can take out the conversion check.  I'm also looking at the other conversions to see if we are preserving the previous behavior correctly.

**Comment by daichimukai** [comment]
@nbalacha @tasleson 
I agree with reverting to the previous behavior.   We'll review the PR. Thanks!

I think it deserves to discuss how lvmd should work when there is an LV or VG that has not been activated. Should lvmd activate it, or should sysadmin activate it? For now, I am considering adopting the latter idea. In this case exporting metrics of number of inactive LV/VG might help so that sysadmin can be aware of such LV/VG.
