### ISSUE TITLE
PVC Created failed (rpc error)

### ISSUE THREAD

**Issue by linux123zc** [topolvm/topolvm#560]
1. PVC Created failed (rpc error)
---

    root@master01:~/topolvm# kubectl describe pvc topolvm-pvc1
    Name:          topolvm-pvc1
    Namespace:     default
    StorageClass:  topolvm-provisioner
    Status:        Pending
    Volume:        
    Labels:        <none>
    Annotations:   volume.beta.kubernetes.io/storage-provisioner: topolvm.cybozu.com
                   volume.kubernetes.io/selected-node: node01
    Finalizers:    [kubernetes.io/pvc-protection]
    Capacity:      
    Access Modes:  
    VolumeMode:    Filesystem
    Used By:       my-pod1
    Events:
      Type     Reason                Age                    From                                                                                         Message
      ----     ------                ----                   ----                                                                                         -------
      Normal   WaitForFirstConsumer  48m                    persistentvolume-controller                                                                  waiting for first consumer to be created before binding
      Warning  ProvisioningFailed    23m                    topolvm.cybozu.com_topolvm-controller-868887bb4f-wjz56_485ed8ce-30a2-4dac-927f-106a814f8bf0  failed to provision volume with StorageClass "topolvm-provisioner": rpc error: code = Internal desc = context deadline exceeded
      Warning  ProvisioningFailed    19m (x14 over 48m)     topolvm.cybozu.com_topolvm-controller-868887bb4f-wjz56_485ed8ce-30a2-4dac-927f-106a814f8bf0  failed to provision volume with StorageClass "topolvm-provisioner": rpc error: code = DeadlineExceeded desc = context deadline exceeded
      Normal   ExternalProvisioning  3m51s (x182 over 48m)  persistentvolume-controller                                                                  waiting for a volume to be created, either by external provisioner "topolvm.cybozu.com" or manually created by system administrator
      Normal   Provisioning          2m45s (x20 over 48m)   topolvm.cybozu.com_topolvm-controller-868887bb4f-wjz56_485ed8ce-30a2-4dac-927f-106a814f8bf0  External provisioner is provisioning volume for claim "default/topolvm-pvc1"

2.  When I delete the LogicalVolume CRD, it is automatically generated again after a while.

**Comment by pluser** [comment]
Thank you for your report.
If you want any advice or discussion, could you please follow the information according to [the template we have provided](https://github.com/topolvm/topolvm/blob/main/.github/ISSUE_TEMPLATE/bug_report.md)?
