### ISSUE TITLE
Read only file system fix; `LVM_SYSTEM_DIR=/tmp`

### ISSUE THREAD

**Issue by Davincible** [topolvm/topolvm#562]
On a read-only filesystem, where `/etc/lvm` is read-only, such as in [Talos Linux](https://www.talos.dev/), the `lvcreate` operations will fail with exit status 5. To fix this, you can set the env `LVM_SYSTEM_DIR=/tmp`, on the lvmd daemon pod. 

Currently there is no easy way to set this in the deployment, as the helm chart doesn't take custom envs. However, perhaps Topolvm could autodetect a read only filesystem and automatically set the env when necessary

**Comment by llamerada-jp** [comment]
Thank you for your post. It looks better to update helm chart to add env value for [lvmd daemonset](https://github.com/topolvm/topolvm/blob/0a0d21052496bf03763424eda0b6556ed99b6147/charts/topolvm/templates/lvmd/daemonset.yaml) by hand. About auto-detect, I am anxious about miss judge when unanticipated situations. I would be happy to make a PR if possible. Is it possible?

**Comment by Davincible** [comment]
I understand the concern. Env option in helm would be the easiest. Would also be good to then mention it in the docs, perhaps the FAQ document.

I figured since if `/etc/lvm` is mounted read-only it will fail anyways, so might as well updated the lvm env
