### ISSUE TITLE
According to READM The md example cannot create a topolvm

### ISSUE THREAD

**Issue by lixiaopengy** [topolvm/topolvm#569]
**Describe the bug**

**Environments**
- Version:
- OS: CentOS Linux release 7.6.1810 (Core)  3.10.0-957.el7.x86_64

**To Reproduce**
![image](https://user-images.githubusercontent.com/65278402/193042112-cb269147-9348-4bb9-9000-76b7f63e7460.png)

#My lvmd is working
[root@k8s1 topolvm]# systemctl status lvmd
● lvmd.service - lvmd for TopoLVM
   Loaded: loaded (/usr/lib/systemd/system/lvmd.service; disabled; vendor preset: disabled)
   Active: active (running) since 四 2022-09-29 20:58:18 CST; 20min ago
  Process: 22253 ExecStartPre=/bin/mkdir -p /run/topolvm (code=exited, status=0/SUCCESS)
 Main PID: 22255 (lvmd)
    Tasks: 8
   Memory: 8.8M
   CGroup: /system.slice/lvmd.service
           └─22255 /opt/sbin/lvmd

9月 29 20:58:18 k8s1 systemd[1]: Starting lvmd for TopoLVM...
9月 29 20:58:18 k8s1 systemd[1]: Started lvmd for TopoLVM.
9月 29 20:58:18 k8s1 lvmd[22255]: 2022-09-29T12:58:18.204238Z k8s1 lvmd info: "configuration file loaded: " device_classes="[0xc0000c2300]" file_name="/etc/topolvm/lvmd.yaml" socket_name="/ru...olvm/lvmd.sock"
Hint: Some lines were ellipsized, use -l to show in full.

#HELM is installed
 [root@k8s1 topolvm]# helm version
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}

#However, the creation through help will show that there is no "helm repo"
[root@k8s1 topolvm]# helm upgrade --namespace=topolvm-system -f values.yaml -i topolvm topolvm/topolvm
Release "topolvm" does not exist. Installing it now.
Error: failed to download "topolvm/topolvm" (hint: running `helm repo update` may help)

Is there any other way to implement this example，Thank you for your help

**Comment by lixiaopengy** [comment]
> 
#Is this problem caused by the network?
[root@single1 topolvm]# helm upgrade --namespace=topolvm-system -f values.yaml -i topolvm topolvm/topolvm
Release "topolvm" does not exist. Installing it now.
Error: failed to download "topolvm/topolvm" (hint: running `helm repo update` may help)

**Comment by daichimukai** [comment]
> Is this problem caused by the network?

I cannot say for certain since it depends on your environment, but I don't think so.

I suspect you didn't add the TopoLVM helm repository.
Please run `helm repo list` to ensure the TopoLVM helm repo is added.

Example:
```
$ helm repo list
NAME        	URL                              
topolvm     	https://topolvm.github.io/topolvm
```

**Comment by lixiaopengy** [comment]
> helm repo list

[root@single1 topolvm]# helm repo list
NAME    URL                              
topolvm https://topolvm.github.io/topolvm
[root@single1 topolvm]#

**Comment by daichimukai** [comment]
What do you get by running `helm repo update`?

Example: 

```
$ helm repo update
...Successfully got an update from the "topolvm" chart repository
Update Complete. ⎈Happy Helming!⎈
$
```

**Comment by lixiaopengy** [comment]
> 跑步能得到什么`helm repo update`？
> 
> 例子：
> 
> ```
> $ helm repo update
> ...Successfully got an update from the "topolvm" chart repository
> Update Complete. ⎈Happy Helming!⎈
> $
> ```

#I have successfully installed topolvm
[root@topolvm topolvm]# kubectl get pod -A 
NAMESPACE        NAME                                               READY   STATUS             RESTARTS       AGE
kube-system      coredns-79dbc7d899-pdz6j                           1/1     Running            0              44m
kube-system      etcd-topolvm                                       1/1     Running            0              45m
kube-system      kube-apiserver-topolvm                             1/1     Running            0              44m
kube-system      kube-controller-manager-topolvm                    1/1     Running            1 (45m ago)    45m
kube-system      kube-flannel-ds-z8hzr                              1/1     Running            0              44m
kube-system      kube-proxy-8h8jg                                   1/1     Running            0              44m
kube-system      kube-scheduler-topolvm                             1/1     Running            1 (45m ago)    45m
topolvm-system   topolvm-cert-manager-6d9bd9685c-tfhtp              1/1     Running            0              9m26s
topolvm-system   topolvm-cert-manager-cainjector-6f5669d57d-qrx2p   1/1     Running            0              9m26s
topolvm-system   topolvm-cert-manager-webhook-86b9f958f7-ztzp4      1/1     Running            0              9m26s
topolvm-system   topolvm-controller-868887bb4f-2hmfj                5/5     Running            0              85s
topolvm-system   topolvm-controller-868887bb4f-lh25h                0/5     Pending            0              84s
topolvm-system   topolvm-lvmd-0-rcmth                               1/1     Running            0              22m
topolvm-system   topolvm-node-4shpl                                 1/3     CrashLoopBackOff   10 (85s ago)   5m6s
topolvm-system   topolvm-scheduler-qfnh7                            1/1     Running            0              22m

#However, I found a problem that csi-topolvm.lock would not be generated in my kubelet directory, which caused my service to fail to start
Events:
  Type     Reason     Age    From               Message
  ----     ------     ----   ----               -------
  Normal   Scheduled  5m26s  default-scheduler  Successfully assigned topolvm-system/topolvm-node-4shpl to topolvm
  Normal   Created    5m25s  kubelet            Created container csi-registrar
  Normal   Started    5m24s  kubelet            Started container liveness-probe
  Normal   Created    5m24s  kubelet            Created container liveness-probe
  Normal   Started    5m24s  kubelet            Started container csi-registrar
  Normal   Pulled     5m24s  kubelet            Container image "ghcr.io/topolvm/topolvm-with-sidecar:0.15.1" already present on machine
  Warning  Unhealthy  5m15s  kubelet            Liveness probe failed: F1001 03:42:26.002278       9 main.go:159] Kubelet plugin registration hasn't succeeded yet, file=/data/kubelet/plugins/topolvm.cybozu.com/node/registration doesn't exist.
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0x1)
  /go/src/github.com/kubernetes-csi/node-driver-registrar/vendor/k8s.io/klog/v2/klog.go:1038 +0x8a
k8s.io/klog/v2.(*loggingT).output(0xf75740, 0x3, 0x0, 0xc0001cea10, 0x0, {0xc83032?, 0x1?}, 0xc0002428d0?, 0x0)
  /go/src/github.com/kubernetes-csi/node-driver-registrar/vendor/k8s.io/klog/v2/klog.go:987 +0x5fd
k8s.io/klog/v2.(*loggingT).printf(0xa8db45?, 0x4?, 0x0, {0x0, 0x0}, {0xab608c, 0x48}, {0xc0002428c0, 0x1, 0x1})
  /go/src/github.com/kubernetes-csi/node-driver-registrar/vendor/k8s.io/klog/v2/klog.go:753 +0x1c5
k8s.io/klog/v2.Fatalf(...)
  /go/src/github.com/kubernetes-csi/node-driver-registrar/vendor/k8s.io/klog/v2/klog.go:1532
main.main()
  /go/src/github.com/kubernetes-csi/node-driver-registrar/cmd/csi-node-driver-registrar/main.go:159 +0x46e

goroutine 20 [runnable]:
k8s.io/klog/v2.init.0.func1()
  /go/src/github.com/kubernetes-csi/node-driver-registrar/vendor/k8s.io/klog/v2/klog.go:420
runtime.goexit()
  /usr/local/go/src/runtime/asm_amd64.s:1571 +0x1
created by k8s.io/klog/v2.init.0
           /go/src/github.com/kubernetes-csi/node-driver-registrar/vendor/k8s.io/klog/v2/klog.go:420 +0xf6
  Normal   Started    5m11s (x3 over 5m25s)  kubelet  Started container topolvm-node
  Normal   Created    5m11s (x3 over 5m25s)  kubelet  Created container topolvm-node
  Normal   Pulled     5m11s (x3 over 5m25s)  kubelet  Container image "ghcr.io/topolvm/topolvm-with-sidecar:0.15.1" already present on machine
  Warning  Unhealthy  5m5s                   kubelet  Liveness probe failed: F1001 03:42:35.987894      17 main.go:159] Kubelet plugin registration hasn't succeeded yet, file=/data/kubelet/plugins/topolvm.cybozu.com/node/registration doesn't exist.
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0x1)
  /go/src/github.com/kubernetes-csi/node-driver-registrar/vendor/k8s.io/klog/v2/klog.go:1038 +0x8a
k8s.io/klog/v2.(*loggingT).output(0xf75740, 0x3, 0x0, 0xc0001cea80, 0x0, {0xc83032?, 0x1?}, 0xc0002c28d0?, 0x0)
  /go/src/github.com/kubernetes-csi/node-driver-registrar/vendor/k8s.io/klog/v2/klog.go:987 +0x5fd
k8s.io/klog/v2.(*loggingT).printf(0xa8db45?, 0x4?, 0x0, {0x0, 0x0}, {0xab608c, 0x48}, {0xc0002c28c0, 0x1, 0x1})
  /go/src/github.com/kubernetes-csi/node-driver-registrar/vendor/k8s.io/klog/v2/klog.go:753 +0x1c5
k8s.io/klog/v2.Fatalf(...)
  /go/src/github.com/kubernetes-csi/node-driver-registrar/vendor/k8s.io/klog/v2/klog.go:1532
main.main()
  /go/src/github.com/kubernetes-csi/node-driver-registrar/cmd/csi-node-driver-registrar/main.go:159 +0x46e

goroutine 20 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0xc0000a8480?)
  /go/src/github.com/kubernetes-csi/node-driver-registrar/vendor/k8s.io/klog/v2/klog.go:1181 +0x6a
created by k8s.io/klog/v2.init.0
           /go/src/github.com/kubernetes-csi/node-driver-registrar/vendor/k8s.io/klog/v2/klog.go:420 +0xf6
  Normal   Pulled     4m55s (x2 over 5m25s)  kubelet  Container image "ghcr.io/topolvm/topolvm-with-sidecar:0.15.1" already present on machine
  Warning  Unhealthy  4m55s                  kubelet  Liveness probe failed: F1001 03:42:45.992886      25 main.go:159] Kubelet plugin registration hasn't succeeded yet, file=/data/kubelet/plugins/topolvm.cybozu.com/node/registration doesn't exist.
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0x1)
  /go/src/github.com/kubernetes-csi/node-driver-registrar/vendor/k8s.io/klog/v2/klog.go:1038 +0x8a
k8s.io/klog/v2.(*loggingT).output(0xf75740, 0x3, 0x0, 0xc0001cca80, 0x0, {0xc83032?, 0x1?}, 0xc0002428e0?, 0x0)
  /go/src/github.com/kubernetes-csi/node-driver-registrar/vendor/k8s.io/klog/v2/klog.go:987 +0x5fd
k8s.io/klog/v2.(*loggingT).printf(0xa8db45?, 0x4?, 0x0, {0x0, 0x0}, {0xab608c, 0x48}, {0xc0002428d0, 0x1, 0x1})
  /go/src/github.com/kubernetes-csi/node-driver-registrar/vendor/k8s.io/klog/v2/klog.go:753 +0x1c5
k8s.io/klog/v2.Fatalf(...)
  /go/src/github.com/kubernetes-csi/node-driver-registrar/vendor/k8s.io/klog/v2/klog.go:1532
main.main()
  /go/src/github.com/kubernetes-csi/node-driver-registrar/cmd/csi-node-driver-registrar/main.go:159 +0x46e

goroutine 20 [runnable]:
k8s.io/klog/v2.init.0.func1()
  /go/src/github.com/kubernetes-csi/node-driver-registrar/vendor/k8s.io/klog/v2/klog.go:420
runtime.goexit()
  /usr/local/go/src/runtime/asm_amd64.s:1571 +0x1
created by k8s.io/klog/v2.init.0
           /go/src/github.com/kubernetes-csi/node-driver-registrar/vendor/k8s.io/klog/v2/klog.go:420 +0xf6
  Normal   Killing  4m55s                 kubelet  Container csi-registrar failed liveness probe, will be restarted
  Warning  BackOff  17s (x42 over 5m23s)  kubelet  Back-off restarting failed container

**Comment by lixiaopengy** [comment]
> What do you get by running `helm repo update`?
> 
> Example:
> 
> ```
> $ helm repo update
> ...Successfully got an update from the "topolvm" chart repository
> Update Complete. ⎈Happy Helming!⎈
> $
> ```

I have successfully deployed topolvm. Thank you for your help
