### ISSUE TITLE
Topolvm tries to delete the LV

### ISSUE THREAD

**Issue by vj0R** [topolvm/topolvm#607]
Topolvm 0.9.1 tries to delete the LV topolvm created by the previous version, but cannot do so because the volume is mounted. If you delete a pod then the LV is deleted.

```
{"level":"error","ts":1668420990.772864,"logger":"controller-runtime.manager.controller.logicalvolume","msg":"failed to remove LV","reconciler group":"topolvm.cybozu.com",   "reconciler kind":"LogicalVolume","name":"pvc-ab2467da-c185-442d-adaf-dce8f5cb0445","namespace":"","name":"pvc-ab2467da-c185-442d-adaf-dce8f5cb0445","uid":"4fd211bd-4e98-4cb5-a44a-db445eea5a81","error":"rpc error: code = Internal desc = exit status 5","stacktrace":"github.com/topolvm/topolvm/controllers.(*LogicalVolumeReconciler).Reconcile\n \t/workdir/controllers/logicalvolume_controller.go:108\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod /sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go                         /pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:214"}
```
logs on working node
```
Nov 22 07:54:08 k8s-01 lvmd: 2022-11-22T04:54:08.502198Z k8s-01.om.com lvmd info: "invoking LVM command" args="[lvremove -f /dev/topolvm/f8415d1f-1399-431e-bb8c-e6670e6229a5]"
Nov 22 07:54:08 k8s-01 lvmd: Logical volume topolvm/f8415d1f-1399-431e-bb8c-e6670e6229a5 contains a filesystem in use.
Nov 22 07:54:08 k8s-01 lvmd: 2022-11-22T04:54:08.544520Z k8s-01.om.com lvmd error: "failed to remove volume" error="exit status 5" name="f8415d1f-1399-431e-bb8c-e6670e6229a5"
```

CentOS Linux release 7.7.1908 (Core)
Linux version 5.18.3-1.el7.elrepo.x86_64
Kubernetes version v1.21.13
Topolvm version 0.9.1

We have updated kubernetes to version 1.21.13
Next, we installed the corresponding topolvm version 0.9.1.
Before that there was a version of topolvm 0.2.0

- `helm delete --namespace=csi-volume topolvm`
- `kubectl delete customresourcedefinitions.apiextensions.k8s.io logicalvolumes.topolvm.cybozu.com`
- `helm install --namespace=csi-volume topolvm . --set cert-manager.enabled=true`

Topolvm perfectly creates pv !
We don't make request for delete pvc !
Why does it remove the pv created by the old topolvm ?
We wouldn't want topolvm to remove LV

**Comment by peng225** [comment]
Hi @vj0R 

> We wouldn't want topolvm to remove LV

This is due to the following command.

> kubectl delete customresourcedefinitions.apiextensions.k8s.io logicalvolumes.topolvm.cybozu.com

Generally, when you delete CRD, all the relevant custom resources are deleted.
Since you deleted the CRD of LogicalVolume, all the LogcalVolume CRs were deleted.

When you upgrade topolvm (or any other application), I think you do not need to delete CRD.
