### ISSUE TITLE
new metrics to let me know that the expansion has failed

### ISSUE THREAD

**Issue by llamerada-jp** [topolvm/topolvm#613]
## What

PVCs have expanded automatically on the environment using topolvm and pvc-autoresizer. However, it isn't easy to notice that the expansion has failed. It is better to add new metrics to detect failures.

It is an example of PVC's events that failed to expand. This message is expected in normal cases too. So it is not good to detect failing expansion by using this message.

```
Events:
  Type    Reason    Age                     From                                 Message
  ----    ------    ----                    ----                                 -------
  Normal  Resizing  105s (x16380 over 19d)  external-resizer topolvm.cybozu.com  External resizer is resizing volume pvc-6d292f89-6c3e-417e-8044-f99ec9435e35
```

## How

Add new metrics to detect failures.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by pluser** [comment]
It is possible to notice volume expansion failures from existing metrics without adding new metrics.
The difference between PV and PVC capacities can be used to know when expansion failure has occurred.
