### ISSUE TITLE
How to remove Topolvm completely from a Kuberenetes cluster?

### ISSUE THREAD

**Issue by saeedkaz** [topolvm/topolvm#645]
### Discussed in https://github.com/topolvm/topolvm/discussions/644

<div type='discussions-op-text'>

<sup>Originally posted by **saeedkaz** January 22, 2023</sup>
We had a Topolvm on our cluster. First I removed all data from it. After that, we tried to remove Topolvm from our cluster but it wasn't successful. I did the following steps First I reduce the replica set of Topolvm to 0 but it was unsuccessful and I get the following error.

MountVolume.SetUp failed for volume "kube-api-access-gvxr4" : object "namespace-test"/"kube-root-ca.crt" not registered 
After that, I deleted the webhook with no success. After that, I deleted the lines about Topolvm in the scheduler which make the cluster unstable.

I am looking for a way to cleanly and completely remove Topolvm from the cluster</div>

**Comment by toshipp** [comment]
we discussed this issue in #644
