### ISSUE TITLE
Add metric for number of PVs in volume group

### ISSUE THREAD

**Issue by Thor77** [topolvm/topolvm#650]
**What should the feature do:**
Add a metric for number of PVs in volume group managed by lvmd

**What is use case behind this feature:**
Check whether all disks of a server are in use by comparing it with count of drives visible to OS or HBA controller

I'm open to implementing this myself if you would accept a PR for this. This would probably require changes to the lvmd protocol as it currently doesn't propagate that information (which should already be available in the output of the lvm commands run for finding information like vg size).

**Comment by daichimukai** [comment]
"PV" stands for "Physical Disk" of LVM, right?

As a CSI plugin, TopoLVM does not need to be aware of the PVs that make up the VG. So I am not sure if this is the preferred method.

**Comment by Thor77** [comment]
@daichimukai PV = physical volume in LVM. It doesn't need to be aware of them or do anything with that information, it would just be nice if that information could be exposed as a metric so it can be used for monitoring purposes.

**Comment by daichimukai** [comment]
@Thor77 
I think such information should be exported by a dedicated exporter such as [prometheus-lvm-exporter](https://github.com/hansmi/prometheus-lvm-exporter), or node-exporter with [the textfile collector for LVM](
https://github.com/prometheus-community/node-exporter-textfile-collector-scripts/blob/6f710f88bb38625657f61aa42d5f61fbdc2b8066/lvm-prom-collector).

**Comment by Thor77** [comment]
@daichimukai I'll look into those options as well, thanks. As I already implemented the patch to see how much effort it would be, I still opened a PR for it but can also understand if it's not accepted.
