### ISSUE TITLE
Upgrade issue from 0.14.1 to 0.15.0

### ISSUE THREAD

**Issue by anupamdutta-314e** [topolvm/topolvm#703]
Hi All,

I am facing issue during tololvm upgradation using helm from 0.14.1 to 0.15.0 getting below error.

"Error: UPGRADE FAILED: cannot patch "topolvm-node" with kind DaemonSet: DaemonSet.apps "topolvm-node" is invalid: spec.template.spec.containers[1].livenessProbe.httpGet: Forbidden: may not specify more than 1 handler type"

My Infra is below:

We have 3 nodes kubernetes cluster. All are muser nodes.
Cluster version: v1.23.5
Cluster is configured through kubeadm. kibeadm, kubelet and kubectl version is v1.23.5.
OS in all nodes: Ubuntu 22.04
I am trying to upgrade by below command.
helm upgrade topolvm topolvm/topolvm --version 9.0.0 -n topolvm-system.
I am getting above error screenshot is attached.
<img width="1429" alt="Screenshot 2023-05-18 at 7 23 47 PM" src="https://github.com/topolvm/topolvm/assets/106244978/bcd25888-7852-4131-bd87-25da1452564f">I appreciate if anyone  suggest how should I proceed.

Thanks 
Anupam

**Comment by peng225** [comment]
Hi @anupamdutta-314e 

`spec.template.spec.containers[1].livenessProbe` corresponds to the following lines of code. This is configured as an exec probe, not http probe for both v0.14.1 and v0.15.0.
https://github.com/topolvm/topolvm/blob/v0.14.1/charts/topolvm/templates/node/daemonset.yaml#L94-L100

However, the error message refers to `spec.template.spec.containers[1].livenessProbe.httpGet`, which is a configuration of http probe.

Have you ever edited the livenessProbe settings of `topolvm-node` DaemonSet manually?

**Comment by anupamdutta-314e** [comment]
Hi Peng225,

No. I don't edited the livenessProbe settings of topolvm-node DaemonSet manually. First I tried to update topolvm 14.0.1 to latest version 0.18.2, But,  I got this error message "Error: UPGRADE FAILED: cannot patch "topolvm-provisioner" with kind StorageClass: StorageClass.storage.k8s.io "topolvm-provisioner" is invalid: provisioner: Forbidden: updates to provisioner are forbidden.". After checking changelog got to know that topolvm-provisioner have been change from topolvm.cybozu.com to topolvm.io from 0.16.0 version. Then I tried to upgrade it from 0.14.1 to 0.15.0 by above commend. Is this created problem. 

Anupam

**Comment by peng225** [comment]
> No. I don't edited the livenessProbe settings of topolvm-node DaemonSet manually. 

O.K. Thanks.

> First I tried to update topolvm 14.0.1 to latest version 0.18.2, But, I got this error message

I followed your procedure and succeeded to reproce the problem.

The livenessProbe  of `csi-registrar` container of `topolvm-node` DaemonSet has been changed since  v0.17.0 (chart version 11.0.1). Because you tried to upgrade to v0.18.2 and it failed, the upgrade seems to be done partially and the livenessProbe of `topolvm-node` has changed.

To fix your system, I suggest to run `helm rollback --force` commad. (without `--force` option, I could not rollback in my envirionment.)

I will show you the example command in my environment.
Please see also [the helm's document](https://helm.sh/docs/helm/helm_rollback/).

History check. Revision 1 is the point where I would like to go back.
```
❯ ./bin/helm history -n topolvm-system topolvm
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/shinya_hayashi/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/shinya_hayashi/.kube/config
REVISION        UPDATED                         STATUS          CHART           APP VERSION     DESCRIPTION                                                                                                                                                                                                                                                                                                                                                                                                         
1               Mon May 22 08:50:53 2023        deployed        topolvm-8.0.1   0.14.1          Install complete                                                                                                                                                                                                                                                                                                                                                                                                    
2               Mon May 22 08:57:17 2023        failed          topolvm-11.2.0  0.18.2          Upgrade "topolvm" failed: cannot patch "topolvm-provisioner" with kind StorageClass: StorageClass.storage.k8s.io "topolvm-provisioner" is invalid: provisioner: Forbidden: updates to provisioner are forbidden. && cannot patch "topolvm-provisioner-thin" with kind StorageClass: StorageClass.storage.k8s.io "topolvm-provisioner-thin" is invalid: provisioner: Forbidden: updates to provisioner are forbidden.
3               Mon May 22 08:57:31 2023        superseded      topolvm-11.2.0  0.18.2          Upgrade "topolvm" failed: cannot patch "topolvm-provisioner" with kind StorageClass: StorageClass.storage.k8s.io "topolvm-provisioner" is invalid: provisioner: Forbidden: updates to provisioner are forbidden. && cannot patch "topolvm-provisioner-thin" with kind StorageClass: StorageClass.storage.k8s.io "topolvm-provisioner-thin" is invalid: provisioner: Forbidden: updates to provisioner are forbidden.
4               Mon May 22 08:58:19 2023        failed          topolvm-8.0.1   0.14.1          Rollback "topolvm" failed: no ClusterRole with the name "topolvm-external-provisioner-runner" found                                                              
```

Roll back to the target revision.
```
❯ ./bin/helm rollback --force -n topolvm-system topolvm 1
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/shinya_hayashi/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/shinya_hayashi/.kube/config
Error: no ClusterRole with the name "topolvm-external-provisioner-runner" found
```

Oops. I hit another error, but it seems to be the transient one. Just retry the command.
```
❯ ./bin/helm rollback --force -n topolvm-system topolvm 1
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/shinya_hayashi/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/shinya_hayashi/.kube/config
Rollback was a success! Happy Helming!
```
```

**Comment by anupamdutta-314e** [comment]
Thanks for your help. I am able to rollback. But, when I am going to upgrade from 0.14.1 to 0.15.0, one of the node(ex-vm-dev-3) topolvm-lvmd, topolvm-node and topolvm-scheduler are not coming up automatically. But, after restart the node these are coming and working fine. Same thing happening for rollback procedure. I am not getting any error. Is there any clue.

**Comment by peng225** [comment]
> Is there any clue.

I have no idea. Were there the DaemonSet resources for lvmd, topolvm-node, and topolvm-scheduler when those pods were not coming up? If so, it may help to see the result of `kubectl describe daemonset` command.

**Comment by anupamdutta-314e** [comment]
Yes.Please close this case.

Regards,
Anupam
