### ISSUE TITLE
Update CSI gRPC proto to spec 1.2.0

### ISSUE THREAD

**Issue by ymmt2005** [topolvm/topolvm#71]
## What

Now that [CSI spec v1.2.0](https://github.com/container-storage-interface/spec/releases/tag/v1.2.0) is released, the gRPC proto file in TopoLVM needs to be updated.

Also, implement additional fields for better conformance.

## How

Describe how to address the issue.

## Technical Information

If `kubelet` adds support for CSI 1.2, TopoLVM should be upgraded too.
See https://github.com/kubernetes/kubernetes/issues/86923 .
It has introduced `VolumeCapability` in `NodeExpandVolumeRequest`.
This can eliminate [TopoLVM's device type checking](https://github.com/topolvm/topolvm/blob/v0.5.2/driver/node.go#L450).

## Checklist

- [ ] Finish implentation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
This task is blocked by https://github.com/kubernetes/kubernetes/issues/86923

**Comment by umezawatakeshi** [comment]
https://github.com/kubernetes/kubernetes/pull/86968 will be released with Kubernetes 1.19. TopoLVM supports three minor versions, so CSI 1.2 support should be added with Kubernetes 1.21 support.

**Comment by toshipp** [comment]
closed via #256
