### ISSUE TITLE
Deploy with ArgoCD: Secret not found

### ISSUE THREAD

**Issue by pasettifabio** [topolvm/topolvm#729]
Hi everybody,

**Description**
when you deploy TopoLVM via ArgoCD (or equivalent CD tools) using Helm Charts, it appends random characters at the end of the secret name so the pods are not able to find the secrets.

**Environments**
- K8s Version: 1.25.9
- TopoLVM Version: 0.19.1
- ArgoCD Version: v2.7.6

**To Reproduce**
1. Deploy TopoLVM using helm via ArgoCD
2. Verify the secret name:
    `kubectl -n topolvm get secrets`
    `helm-chart-topolvm-mutatingwebhook-m84jv`
3. Describe TopoLVM Controller pods in crash:
    `kubectl -n topolvm describe pod/helm-chart-topolvm-controller-cdfb584c8-xpz5z`
    `MountVolume.SetUp failed for volume "certs" : secret "helm-chart-topolvm-mutatingwebhook" not found`

**Expected behavior**
I'm expecting the Pods are able to read the secret name even if it is generated from a CD tool as ArgoCD.

**Comment by daichimukai** [comment]
Hi @pasettifabio,

Can you please check the status of Certificate resource? That secret is expected to be generated by cert-manager from the Certificate resource, so there may be errors in that process.
