### ISSUE TITLE
LVM on top of another PVC

### ISSUE THREAD

**Issue by stevefan1999-personal** [topolvm/topolvm#740]
**What should the feature do:**

Let us setup lvmd with another block PVC though other means

**What is use case behind this feature:**

I can create a block volume on OCI, but with a minimum of 50GB per block volume. As I have 200GB free quota, this only means I can only have 4 block volumes. I clearly needed more than that. Since I would be running on a single node solely, having LVM access on top of a PVC attached from OCI is the most suitable, but I just didn't see the options here likeso.

I remember the OCI PVC can be freely migrated to different VMs using iSCSI. So basically we don't need NFS for that. This technique can be ported to other cloud platforms as a competitor to Rook/Ceph if we can support LVM on top of another block based PVC. I do understand the pros and cons of Ceph (as I should be using RBD as an alternative here)

**Comment by suleymanakbas91** [comment]
Unfortunately, this feature is also not in the roadmap of the LVM Operator.
