### ISSUE TITLE
Wait for Pod's graceful shutdown to delete data

### ISSUE THREAD

**Issue by cupnes** [topolvm/topolvm#745]
## What

Currently, topolvm does not wait for a graceful shutdown of the Pod to delete data.

## How

The consideration of how to address this issue is also a task in this issue.

The following is an idea.

- Use the eviction API instead of the delete API.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by llamerada-jp** [comment]
this issue can be resolve by https://github.com/topolvm/topolvm/issues/748
