### ISSUE TITLE
Volume encryption

### ISSUE THREAD

**Issue by jimmyjones2** [topolvm/topolvm#76]
## What

Encrypt volumes provisioned by topolvm

## How

eg. LUKS

Generate per-PVC encryption keys, stored as Kubernetes secrets.

The threat this would mitigate is physical theft of server (as keys are only kept in memory)

**Comment by satoru-takeuchi** [comment]
It looks nice. However, my teams uses encrypted disks as topolvm's backend devices and no  strong motivation to support this feature for now.

If you send PR to support volume encryption feature, we'd like to review it!

**Comment by AlexAndrascu** [comment]
> It looks nice. However, my teams uses encrypted disks as topolvm's backend devices and no  strong motivation to support this feature for now.
> 
> If you send PR to support volume encryption feature, we'd like to review it!

Can you please add a short example on how to achieve the above? Also many thanks for writing Topolovm ! 🙏
