### ISSUE TITLE
Upgrading the logging library of lvmd

### ISSUE THREAD

**Issue by jakobmoellerdev** [topolvm/topolvm#773]
**What should the feature do:**

Allow configuring lvmd logging via klog or controller-runtime.

**What is use case behind this feature:**

Currently the logging library of lvmd is based on the archived https://github.com/cybozu-go/log library. Nowadays all other parts of topolvm are either using klog or controller-runtime logr implementations.

It is also apparent why. The majority of features found in klog / controller-runtime are not supported in lvmd and unifying and scraping logs is hard to accomplish.

**Comment by peng225** [comment]
Though I don't know why `cybozu-go/log` is used, I guess that is for historical reasons.
As you know, that has been already archived, so I agree to replace it with other logging libraries.

**Comment by jakobmoellerdev** [comment]
Awesome! Will this be tackled by you @cupnes or should I take care of that?

**Comment by satoru-takeuchi** [comment]
I'll ask @cupnes tomorrow. Today, he is on PTO.

**Comment by cupnes** [comment]
@jakobmoellerdev May I leave this to you? I will review it.
