### ISSUE TITLE
Hot Reloading lvmd.conf

### ISSUE THREAD

**Issue by jakobmoellerdev** [topolvm/topolvm#785]
**What should the feature do:**

Currently, topolvm-node reads out lvmd.conf file into a global variable on startup based on a command-line flag. In our tests we already bind the file to a config map instead. However, any changes to the config maps or the file after topolvm-node has been started don't get respected until a restart. It would be great to include a "hot-reload" functionality into lvmd.conf that is able to take care of reloading topolvm-node when the content changes.

Ways to solve this:
1. Introduce a file hot reloading mechanism and a simple interface to always get the latest result when using it in topolvm-node
2. Restart topolvm-node automatically when changes have been detected.

**What is use case behind this feature:**
Use case is that we have changing lvmd config entries after initial configuration and startup time. We can call it a part of normal "day-2-operations" in topolvm.

We are happy to provide a solution if the use case is accepted.

**Comment by llamerada-jp** [comment]
Thank you for your post.

I suggest you to use [Reloader](https://github.com/stakater/Reloader). It is often referred to in similar posts such as the following.
- https://github.com/kubernetes/kubernetes/issues/22368
- https://stackoverflow.com/questions/37317003/restart-pods-when-configmap-updates-in-kubernetes

This product is generic and will help if you are having similar problems with other products.

**Comment by llamerada-jp** [comment]
lvmd.yaml is not global. It intends to configure settings on a per-node basis. For example, when using groups of nodes with different specs, we intended to have a different lvmd.yaml. It was difficult to write such settings in Helm, which may have been misleading you.
And, it was expected that lvmd.yaml would not need to be changed unless the hardware of the individual node or device class was changed. Therefore, the hot-reload was not considered necessary.

**Comment by jakobmoellerdev** [comment]
> lvmd.yaml is not global. It intends to configure settings on a per-node basis. For example, when using groups of nodes with different specs, we intended to have a different lvmd.yaml. 

I think that this is not a common use case because the bug with the default device class missing and causing configuration failures for different nodes was only discovered a few days ago.

> It was difficult to write such settings in Helm, which may have been misleading you. And, we expected that lvmd.yaml would not need to be changed unless the hardware of the individual node or device class was changed. Therefore, we had not considered the hot-reload necessary.

I understand. However, even if a volume group gets changed we would need to restart topolvm-node and thus have downtime which we would like to avoid. The tool you suggested just automates the restart, which is not something we want / need.

If you want, we can hide this functionality behind a feature flag if required.

**Comment by toshipp** [comment]
I don't understand why you're worried about downtime. When we update the image, the pods are restarted, so the downtime is unavoidable.
I think reading lvmd.conf at boot time is better to keep the implementation clean and simple.

**Comment by jakobmoellerdev** [comment]
> I don't understand why you're worried about downtime. When we update the image, the pods are restarted, so the downtime is unavoidable. I think reading lvmd.conf at boot time is better to keep the implementation clean and simple.

A downtime during an upgrade is unavoidable, yes. But that is part of regular maintenance of normal SRE maintenance windows in any operational cluster right? I am talking about changes of configurations.

Either way, this is not a major issue for us. We will integrate it in lvm-operator and trigger a restart from there based on a file-watch. It does not complicate our logic so its okay not to have in upstream for us and we're not pushing for it.

I still think there is room for improvement here. How do you protect users from expecting that the correct configuration is used when topolvm-node is not restarted?

**Comment by llamerada-jp** [comment]
> A downtime during an upgrade is unavoidable, yes. But that is part of regular maintenance of normal SRE maintenance windows in any operational cluster right? I am talking about changes of configurations.

It's not so often to change configurations for most users. So, I guess it's acceptable to wait for downtime during pod restart to read topolvm.conf.

> Either way, this is not a major issue for us. We will integrate it in lvm-operator and trigger a restart from there based on a file-watch. It does not complicate our logic so its okay not to have in upstream for us and we're not pushing for it.

Thanks, I'm glad if you do so.

> I still think there is room for improvement here. How do you protect users from expecting that the correct configuration is used when topolvm-node is not restarted?

It can also be said for all applications which don't support the hot-reload of configuration files.

It might be nice to write this behavior in the document. For instance, Rook does so.

https://github.com/rook/rook/blob/master/Documentation/Storage-Configuration/Advanced/ceph-configuration.md#custom-cephconf-settings
```
If you add the settings to the ConfigMap after the cluster has been initialized, each daemon will need to be restarted where you want the settings applied:
```

**Comment by jakobmoellerdev** [comment]
Closing as per discussion above

**Comment by jakobmoellerdev** [comment]
I would like to reopen this discussion here after trying this feature out a bit. I believe that it is reasonably simple to move the current configuration approach into a hot reloading one while keeping the default behavior. PTAL at my branch: https://github.com/topolvm/topolvm/compare/main...jakobmoellerdev:topolvm:hot-reload-lvmd this is about 350 LOC (including some simple tests) and should be easy enough for the project to maintain

**Comment by llamerada-jp** [comment]
I discussed this feature carefully with other maintainers. However, unfortunately, we decided
not to accept the current approach. We still consider that the benefit of this feature is not so big.
It's enough to restart to reload configs since this daemon should only be available upon starting
new pods and users wouldn't mind a bit larger lager latency than 1s.

Although 350LOC might be small, the effect is big because we should keep in mind
that the configuration might be changed at any time. It's a big difference from the current code.

Considering these points, I propose the following changes.

- Make subMain and healthSubMain public.
- Add the `config` argument to these two functions and remove the global `config` variable.

This approach enables you to implement a new controller to achieve a hot reload.

**Comment by jakobmoellerdev** [comment]
I was hoping you would accept the change considering that it is off by default. We do not have to remove the current codeline for this to go in and get tested. I do not have a benefit of your suggestion because I can already implement hot reloading today in downstream without this

**Comment by llamerada-jp** [comment]
I have been surveying the practice of using ConfigMap. The following issues highlight safety concerns that could be better managed with rolling updates:
https://github.com/kubernetes/kubernetes/issues/20200
https://github.com/kubernetes/kubernetes/issues/27081

During this surveying, I observed that the hot reload and incorrect configurations could cause the service to cease functioning entirely. Administrators may consider using a Reloader if they wish to avoid manual operations. However, the risk should be assessed at each site.

I believe it is better not to include risky functions in infrastructure software, especially when similar functions can be achieved using external software.

**Comment by jakobmoellerdev** [comment]
The issues you mentioned imo have significantly different perogatives, they work on Kubernetes desired state loops through replica sets, while the lvmd.yaml works plainly through a configMap. The reason https://github.com/kubernetes/kubernetes/issues/27081 is different is because here there are multiple controllers in between. Currently lvmd.yaml could be changed in the specification of the configMap, but nothing would trigger another "rollout" as it would happen with a replicaSet in a deployment.

> I observed that the hot reload and incorrect configurations could cause the service to cease functioning entirely

what do you mean by that? of course incorrect configurations cause the service to stop working, but that is not impacted by hot reloading at all. There is no case in which an administrator willingly puts out an intermediary state that has an invalid configuration which he wants to avoid rolling out with a manual reload.

> I believe it is better not to include risky functions in infrastructure software, especially when similar functions can be achieved using external software.

I agree, however I fundamentally disagree that hot-reloading a file is a risky functionality, especially if turned off by default. Maybe I am still missing some perspective, can you give me a concrete example in which the hot-reloading itself is the problem? (and not the misconfiguration being stored without being applied)

**Comment by llamerada-jp** [comment]
After further discussions with team members, we have concluded that it is difficult to accept the hot reload feature. The main reasons are as follows:

- Currently, we assume that the settings do not change dynamically. We are not certain that existing functions work correctly under dynamic changes, and the benefits are small relative to the effort required to confirm them. Additionally, we would need to consider this behavior in future designs.
- Even if the feature is disabled by default, we need to pay attention to the behavior mentioned above for people who enable this feature.

My previous post was about the philosophy that Kubernetes uses rolling updates rather than hot reloads. I mentioned that the risk of hot reloads is not the main reason. I apologize for any confusion this may have caused.

**Comment by jakobmoellerdev** [comment]
:crying_cat_face: well here goes that then. Lets close the issue out for good.
