### ISSUE TITLE
helm chart error

### ISSUE THREAD

**Issue by Lanyujiex** [topolvm/topolvm#790]
**Describe the bug**
After I pull out the chart with help. I installed this chart locally and encountered an error, which I did encounter when using Lint.
```
==> Linting ./topolvm
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: parse error at (topolvm/templates/scheduler/poddisruptionbudget.yaml:1): unclosed action

Error: 1 chart(s) linted, 1 chart(s) failed
```
the chart and helm info:
```
# helm repo list  | grep topo
topolvm            	https://topolvm.github.io/topolvm

# md5sum topolvm-12.1.0.tgz 
dbadbe9a3d987465f3d549fc9b167dc5  topolvm-12.1.0.tgz

# helm version 
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}
```

**Expected behavior**

**Additional context**

**Comment by Lanyujiex** [comment]
remove the line breaks in this file and combine them into one line。

It will be able to be resolved

**Comment by pluser** [comment]
Thanks for the report.

Unfortunately, I was not able to reproduce it. Could you please show me the contents of the file topolvm/templates/scheduler/poddisruptionbudget.yaml?

Possibly, the version of the helm cli is out of date. What happens if I run it with a newer helm?

**Comment by pluser** [comment]
Thanks for showing me the file. The content itself looks fine.
And I was able to reproduce the same problem with the same version of Helm 3.4.2 as yours. However, the problem did not occur with my local Helm 3.12.3.
Could you please update your Helm and try again?

**Comment by Lanyujiex** [comment]
> Thanks for showing me the file. The content itself looks fine. And I was able to reproduce the same problem with the same version of Helm 3.4.2 as yours. However, the problem did not occur with my local Helm 3.12.3. Could you please update your Helm and try again?

I tried on another machine and there was no problem either. The Helm version on this machine is
```
[root@dev ~]# helm version
version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.17.5"}
```
This problem is probably due to a problem with the HELM of that machine. I will upgrade my machine's Helm to avoid this problem. 
Thank you!
