### ISSUE TITLE
doc: clarification

### ISSUE THREAD

**Issue by ryanfaircloth** [topolvm/topolvm#821]
More clear requirements for the node OS image may be helpful to myself and others lvmd because it uses nsenter to execute commands on the host requires /sbin/lvm to exist AL2 and BottleRocket AMIs do not include this component but ubuntu does.

**Comment by daichimukai** [comment]
We specify LVM2 as a requirement in README.md. What exactly do you have in mind when you say "More clear requirements"?

> Node OS: Linux with LVM2 (*1)

**Comment by ryanfaircloth** [comment]
Good question I think examples of known good and known not good node choices as a non exhaustive list. In my case I assume (yeah I know) that AL2 on EKS would have LVM because AL2 EC2 AMIS do but it does not, neither does bottlerocket I would either need to build a AL2/Bottlerocket AMI with the added lvm2 or switch to ubuntu which is what I did.
