### ISSUE TITLE
Tacking issue undocumented "policy" causes increased build time and additional time tracking and updating dependencies

### ISSUE THREAD

**Issue by ryanfaircloth** [topolvm/topolvm#822]
We have a policy to build sidecar containers from source code. Since it's not documented, we'll state this policy if necessary.

_Originally posted by @satoru-takeuchi in https://github.com/topolvm/topolvm/issues/819#issuecomment-1894783498_

**Comment by satoru-takeuchi** [comment]
Could you fix the subject and the description of this issue? I do not handle such the issue that the title is just a copy-and-pasted sentences from another issue.

Please stop making maintainers pay high communication costs.

**Comment by ryanfaircloth** [comment]
@satoru-takeuchi in the context your replied that the project has a policy which is not documented but fairly different than similar other projects. What could have saved some steps would have been opening the issue to track yourself rather than reply.

**Comment by satoru-takeuchi** [comment]
I'll state the policy about building sidecar containers by our own in the official document.
