### ISSUE TITLE
Revisiting Limitation on Reclaim Policy

### ISSUE THREAD

**Issue by jakobmoellerdev** [topolvm/topolvm#869]
**What should the change do:**

In the [current TopoLVM limitations](https://github.com/topolvm/topolvm/blob/93059ac6dd8e17b2215bf94ea7789b5d74558583/docs/limitations.md?plain=1#L12-L22) we state that

> TopoLVM does not care about `Retain` [reclaim policy](https://kubernetes.io/docs/concepts/storage/storage-classes/#reclaim-policy)
because CSI volumes can be referenced only via PersistentVolumeClaims.

However when looking at the Retain Policy we read the following:

> The Retain reclaim policy allows for manual reclamation of the resource. When the PersistentVolumeClaim is deleted, the PersistentVolume still exists and the volume is considered "released". But it is not yet available for another claim because the previous claimant's data remains on the volume. An administrator can manually reclaim the volume with the following steps.

IMO this means that TopoLVM fully supports Retain since we do not remove the LogicalVolume automatically and we should not list it under limitations.

**What is use case behind this feature:**

Retain is already respected by TopoLVM and imo should not be considered a limitation.

**Comment by ushitora-anqou** [comment]
Thank you for pointing this out! My teammates and I agree with you and that we should remove this description from the limitations. I'll create a PR to fix this.
