### ISSUE TITLE
Docs: Introduction to creating a PR to topolvm

### ISSUE THREAD

**Issue by guettli** [topolvm/topolvm#893]
**What should the feature do:**

I would like to see some documentation, about how to create a PR for topolvm.

Other projects use tools like Tilt.

How do you develop the Go code. I run `make multi-platform-image-normal` which takes ~60 seconds even if no code was changed.

I guess you use some other workflow to modify the source code (and test it in a cluster).

**What is use case behind this feature:**

I want to enhance topolvm.

**Comment by llamerada-jp** [comment]
There is a contribution guide, but it may be out of date. If you try it and find anything wrong, I would be happy to have it pointed out.
https://github.com/topolvm/topolvm/blob/main/CONTRIBUTING.md

We have tried to introduce tilt before and it was abandoned. It may be helpful to you.
https://github.com/topolvm/topolvm/issues/405
https://github.com/topolvm/topolvm/pull/434

**Comment by guettli** [comment]
@llamerada-jp thank you for your reply. I have seen that topolvm has many envTests. I like that! This way I can test my code easily, and I don't need to build a container and upload it into a cluster often.

For me Tilt is handy, when I need to develop something in a running dev cluster (for example bare-metal).

Because of the good test coverage, Tilt is not needed for me here. The contribution page is all I need.

Thank you for your reply.
