### ISSUE TITLE
lvmd hardcodes binary paths, crashes in nixos

### ISSUE THREAD

**Issue by mlazowik** [topolvm/topolvm#908]
lvmd assumes that lvm is in `/sbin/lvm`, similarly with some other binaries. This is not true in e.g. nixos

**Environments**
- Version: `ghcr.io/topolvm/topolvm-with-sidecar:0.29.0`, chart `14.1.2`
- OS: nixos

**To Reproduce**
1. Deploy lvmd as DaemonSet on k8s with nixos nodes
2. lvmd crashes with `"failed to run command","error":"exit status 127: nsenter: failed to execute /sbin/lvm: No such file or directory"`

**Expected behavior**
One option could be to provide binary path in config/cli arg.

**Comment by toshipp** [comment]
Thank you for your report.
Your suggestion is valid. We'll fix it. Also, problems like those you filed can be raised on different host distributions which we don't use on CI, so we'll denote our testing distribution.
