### ISSUE TITLE
Setting log verbosity to lvmd pod errors out

### ISSUE THREAD

**Issue by Sunnatillo** [topolvm/topolvm#941]
<!--
```
Defaulted container "lvmd" out of: lvmd, topolvm-metrics, volume-group-manager (init)
Error: unknown flag: --v
Usage:
unknown flag: --v
  lvmd [flags]
  lvmd [command]

```  -->
**What should the feature do:**

I want to contribute to this project to improve verbosity of the logs, which would help users to set verbosity logs to their desired level.  I want to get the opinions of the maintainers first. 
For example, following logs is too noisy:
```
{"level":"info","ts":"2024-07-19T04:17:03Z","msg":"invoking LVM command","args":["fullreport","--reportformat","json","--units","b","--nosuffix","--configreport","vg","-o","vg_name,vg_uuid,vg_size,vg_free","--configreport","lv","-o","lv_uuid,lv_name,lv_full_name,lv_path,lv_size,lv_kernel_major,lv_kernel_minor,origin,origin_size,pool_lv,lv_tags,lv_attr,vg_name,data_percent,metadata_percent,pool_lv","--configreport","pv","-o,","--configreport","pvseg","-o,","--configreport","seg","-o,"]}
{"level":"info","ts":"2024-07-19T04:17:03Z","msg":"invoking LVM command","args":["fullreport","--reportformat","json","--units","b","--nosuffix","--configreport","vg","-o","vg_name,vg_uuid,vg_size,vg_free","--configreport","lv","-o","lv_uuid,lv_name,lv_full_name,lv_path,lv_size,lv_kernel_major,lv_kernel_minor,origin,origin_size,pool_lv,lv_tags,lv_attr,vg_name,data_percent,metadata_percent,pool_lv","--configreport","pv","-o,","--configreport","pvseg","-o,","--configreport","seg","-o,"]}
```
**What is use case behind this feature:**

**Comment by llamerada-jp** [comment]
Using verbosity is a good way to reduce logging. k8s has the following documentation that may be helpful.
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md#what-method-to-use
As a TopoLVM-specific matter, I would like to output logs of commands involving lvm changes in the default log level. And commands not involving lvm changes as you point out,  V(4) or V(5) looks better.

**Comment by jakobmoellerdev** [comment]
@Sunnatillo let us know if you want to provide a PR, otherwise we will prepare an adjustment ourselves

**Comment by Sunnatillo** [comment]
> @Sunnatillo let us know if you want to provide a PR, otherwise we will prepare an adjustment ourselves

I have opened a PR to set verbosity to "invoking command" log
