### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by AQuack** [topolvm/topolvm#952]
**Describe the bug**
Running the commands as written [here](https://github.com/topolvm/topolvm/blob/main/docs/getting-started.md#install-instructions) for installing topolvm and cert-manager fail with a 404 .

**Environments**
- Version: v1.15.2
- OS: fedora 40

**To Reproduce**
1. Go to https://github.com/topolvm/topolvm/blob/main/docs/getting-started.md#install-instructions
2. Click on 
![image](https://github.com/user-attachments/assets/6eb83b62-240d-4810-b25a-14764fee7a4a)
Click on the clipboard, or copy+paste the code block for `If you want to install cert-manager together, use the following command instead.`
3.Run the command, fails immediately

**Expected behavior**
To not do that, Ideally it would download the crds

**Additional context**
it seems it my case the issue was specifically with `${VERSION}`  I changed the url to `https://github.com/cert-manager/cert-manager/releases/download/v1.15.2/cert-manager.crds.yml` and move forward

**Comment by toshipp** [comment]
Thank you for your feedback. We'll update doc.
