### ISSUE TITLE
Volume Expansion Failure for FileSystem PVCs After Upgrading to TopoLVM v0.33.0

### ISSUE THREAD

**Issue by daichimukai** [topolvm/topolvm#955]
**Describe the bug**

After upgrading TopoLVM to v0.33.0, we are experiencing resize failures for PVCs with `volumeMode: FileSystem`. Such PVCs are being mounted by some Pods before upgrading TopoLVM to v0.33.0. On the other hand, the PVCs mounted after upgrading TopoLVM to v0.33.0 are successfully resized.

We observe the topolvm-node log messages like the following ones repeatedly.

```json
{
  "level": "info",
  "ts": "2024-08-21T01:23:13Z",
  "logger": "driver.node",
  "msg": "triggering filesystem resize",
  "volume_id": "7e4a960b-9e58-4c76-84c2-c9ce6746357b",
  "volume_path": "/var/lib/kubelet/pods/eb94c444-04dd-4853-af75-395ba13939a0/volumes/kubernetes.io~csi/pvc-63c9abb3-7760-4adf-9f60-b98a217763b5/mount",
  "required": 37580963840,
  "limit": 0,
  "device": "/dev/topolvm/7e4a960b-9e58-4c76-84c2-c9ce6746357b"
}
{
  "level": "error",
  "ts": "2024-08-21T01:23:13Z",
  "msg": "error on grpc call",
  "method": "/csi.v1.Node/NodeExpandVolume",
  "error": "rpc error: code = Internal desc = failed to resize filesystem 7e4a960b-9e58-4c76-84c2-c9ce6746357b (mounted at: /var/lib/kubelet/pods/eb94c444-04dd-4853-af75-395ba13939a0/volumes/kubernetes.io~csi/pvc-63c9abb3-7760-4adf-9f60-b98a217763b5/mount): resize of device /dev/vg1/7e4a960b-9e58-4c76-84c2-c9ce6746357b failed: exit status 1. resize2fs output: resize2fs 1.46.5 (30-Dec-2021)\nresize2fs: Device or resource busy while trying to open /dev/vg1/7e4a960b-9e58-4c76-84c2-c9ce6746357b\nCouldn't find valid filesystem superblock.\n",
  "stacktrace": "github.com/topolvm/topolvm/cmd/topolvm-node/app.ErrorLoggingInterceptor\n\t/workdir/cmd/topolvm-node/app/run.go:202\ngithub.com/container-storage-interface/spec/lib/go/csi._Node_NodeExpandVolume_Handler\n\t/go/pkg/mod/github.com/container-storage-interface/spec@v1.9.0/lib/go/csi/csi.pb.go:7315\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.58.3/server.go:1374\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.58.3/server.go:1751\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.1\n\t/go/pkg/mod/google.golang.org/grpc@v1.58.3/server.go:986"
}
```

**Environments**

- Version: TopoLVM v0.33.0 (Chart version v15.2.0)
- OS: Flatcar Container Linux by Kinvolk 3815.2.5 (or some version like this)

**To Reproduce**

Steps to reproduce the behavior (theoretically):

1. Deploy TopoLVM v0.32.0.
2. Create a PVC (say `test-pvc`) with `volumeMode: FileSystem` and mount it in some Pod.
3. Upgrade TopoLVM to v0.33.0.
4. Resize `test-pvc` by increasing `spec.resources.request.storage`.
5. Check `status` of `test-pvc`.

**Expected behavior**

TopoLVM succeeds to resize filesystems that are being mounted before upgrading TopoLVM to v0.33.0.

**Additional context**

In my environment, resizes succeed after restarting (i.e. the admin deletes and some controller recreates) the Pods which were mounting in-trouble PVCs.

**Comment by jakobmoellerdev** [comment]
I think this might be due to https://github.com/topolvm/topolvm/pull/930 I think the implementation might have an issue with post-upgrade resizing due to the device Path?

**Comment by jakobmoellerdev** [comment]
This looks like a lv path /dev/vg1/7e4a960b-9e58-4c76-84c2-c9ce6746357b, one way to check if this is correct is if that path is discoverable on the node on this path, or if this is still using an old path.

**Comment by daichimukai** [comment]
`/dev/vg1/7e4a960b-9e58-4c76-84c2-c9ce6746357b` was discoverable.

When we were using TopoLVM v0.32.0 (chart v15.1.1), topolvm-node didn't mount host path's `/dev`, so it was a tmpfs. topolvm-node created `/dev/topolvm/7e4a960b-9e58-4c76-84c2-c9ce6746357b` in the tmpfs to mount the volume in some Pod, which were lost after upgrading TopoLVM to v0.33.0.

After upgrade, topolvm-node no longer creates device files under `/dev/topolvm`. When topolvm-node tries to resize `/dev/vg1/7e4a960b-9e58-4c76-84c2-c9ce6746357b`, there's still a Pod mounting that LV via `/dev/topolvm/7e4a960b-9e58-4c76-84c2-c9ce6746357b`, which might cause an error.

**Comment by llamerada-jp** [comment]
> Hmm I wonder if an mknod / device mapper refresh of the nodes could solve this?

Could you please provide a bit more explanation of how this is?

We'd like to let users know that this problem can be fixed by restarting problematic pods. Any comments?
We hesitate to fix this problem because of the following reasons.

- This problem won't happen again after the pod restarts.
- Fixing this introduces complexity. The possible fix is re-creating deleted device files again.

**Comment by jakobmoellerdev** [comment]
> Could you please provide a bit more explanation of how this is?

As I understand the mounts that are active should not be affected by an mknod call, its just that the container namespace might need to be updated when a device is mounted at a different path. I believe mount paths should be able to update.

See 
```
dmsetup mknodes [device_name...]
              Ensure that the node in /dev/mapper for device_name is correct.  If no device_name is sup‐
              plied,  ensure that all nodes in /dev/mapper correspond to mapped devices currently loaded
              by the device-mapper kernel driver, adding, changing or removing nodes as necessary.
```

(Disclaimer I did not try this since I dont have such an environment as you sitting here, but you may want to try around with it to see if you can circumvent that restart)

**Comment by llamerada-jp** [comment]
@jakobmoellerdev 
Sorry for the late reply.

We tried the command you gave me, but it does not seem to affect to `/dev/topolvm` and the error could not be avoided.

I have also added information about the issue to the release page.

**Comment by daichimukai** [comment]
I've confirmed the caveat in [the release note](https://github.com/topolvm/topolvm/releases/tag/v0.33.0). Thanks.
