### ISSUE TITLE
Support multiple deployments of LVMD

### ISSUE THREAD

**Issue by TroyKomodo** [topolvm/topolvm#973]
**What should the feature do:**

I have 2 node groups:
- database
- monitoring

I would ideally like to have 2 storage classes:
- database (for database nodes)
- monitoring (for monitoring nodes)

Each node has its own lvm group
- database: database-raid-lvm
- monitoring: monitoring-raid-lvm

Is this possible with the current state of topolvm?

**Comment by ushitora-anqou** [comment]
Let me try to get a clearer understanding of your situation. Does each of your nodes have two LVM VGs, or just one? In other words, which of the following architectures is correct?

Architecture 1: Each node has two LVM VGs, like this:

- Node A:
  - LVM VG: database-raid-lvm
  - LVM VG: monitoring-raid-lvm
- Node B:
  - LVM VG: database-raid-lvm
  - LVM VG: monitoring-raid-lvm
- ...

Architecture 2: Each node has one LVM VG, like this:

- Node A (database):
  - LVM VG: database-raid-lvm
- Node B (monitoring):
  - LVM VG: monitoring-raid-lvm
- ...

If you mean Architecture 1, you can use two different device classes to separate their storage classes. Check out [this document](https://github.com/topolvm/topolvm/blob/3ddfec27480ca0381c6b0ec4b9e536afdff1aad6/docs/advanced-setup.md#storageclass) for more info.

If you mean Architecture 2, you can use [`lvmd.additionalConfigs` in values.yaml](https://github.com/topolvm/topolvm/blob/3ddfec27480ca0381c6b0ec4b9e536afdff1aad6/charts/topolvm/values.yaml#L194-L203). See also #555 for more details.

**Comment by TroyKomodo** [comment]
Architecture 2 is what I was looking for perhaps we should add that to the advanced use case documentation. Thank you! I assume this also does not work correctly with embedded ohms because we are specifying node affinity / selectors and if we use embedded we specify both nodes in the affinity on the topolvm-node affinity. So it wouldn't be able to have a different config on those nodes. However this is fine and I have it working in my cluster.

**Comment by ushitora-anqou** [comment]
Thank you for your feedback! I've just opened a new PR https://github.com/topolvm/topolvm/pull/975 so that we can describe this advanced setup.
