### ISSUE TITLE
device_classes only support one device-class defualt

### ISSUE THREAD

**Issue by xuegege5290** [topolvm/topolvm#992]
**Describe the bug**
[root@j15-u82-csg-worker0 ccadmin]# crictl logs  6941ce83f497b
2024-11-12T01:32:19.940274Z topolvm-node-bg76v lvmd info: "configuration file loaded: " device_classes="[0xc0002d9f80 0xc000258000]" file_name="/etc/topolvm/lvmd.yaml" socket_name="/run/lvmd/lvmd.sock"
Error: should have only one default device-class

**Expected behavior**
support more device-class

**Comment by xuegege5290** [comment]
From this discussion https://github.com/topolvm/topolvm/issues/973, I see that it supports multiple device-classes.

**Comment by xuegege5290** [comment]
Should I configure this from the perspective of the configuration file, or do I need to remove the judgment in the ValidateDeviceClasses function?
```go
if countDefault > 1 {
return errors.New("should not have multiple default device-class")
}
```

**Comment by xuegege5290** [comment]
@ushitora-anqou I need help. If I'm disturbing you, I apologize.

**Comment by xuegege5290** [comment]
[root@j15-u82-csg-worker0 ccadmin]# cat /etc/topolvm/lvmd.yaml 
device-classes:
- default: true
  lvcreate-options: null
  name: ccos-compute
  spare-gb: null
  stripe: null
  stripe-size: ""
  thin-pool: null
  type: thick
  volume-group: ccos-compute
- default: true
  lvcreate-options: null
  name: ccos-database
  spare-gb: null
  stripe: null
  stripe-size: ""
  thin-pool: null
  type: thick
  volume-group: ccos-database
socket-name: /run/lvmd/lvmd.sock

**Comment by xuegege5290** [comment]
The lvmd.yaml file generated by the lvm-operator. How to configure this, I am confused.

**Comment by ushitora-anqou** [comment]
Hi.

> ```
> [root@j15-u82-csg-worker0 ccadmin]# cat /etc/topolvm/lvmd.yaml 
> device-classes:
> - default: true
>   lvcreate-options: null
>   name: ccos-compute
>   spare-gb: null
>   stripe: null
>   stripe-size: ""
>   thin-pool: null
>   type: thick
>   volume-group: ccos-compute
> - default: true
>   lvcreate-options: null
>   name: ccos-database
>   spare-gb: null
>   stripe: null
>   stripe-size: ""
>   thin-pool: null
>   type: thick
>   volume-group: ccos-database
> socket-name: /run/lvmd/lvmd.sock
> ```

As you've already pointed out, it looks like your lvmd.yaml has two device classes marked as default (`default: true`). It should have only one default entry.

> The lvmd.yaml file generated by the lvm-operator. How to configure this Default flag, I am confused.

Unfortunately, I can't provide any useful information about the lvm-operator since it's not a TopoLVM project. Maybe you could reach out to the maintainers of the lvm-operator for help?

**Comment by xuegege5290** [comment]
> Hi.
> 
> > ```
> > [root@j15-u82-csg-worker0 ccadmin]# cat /etc/topolvm/lvmd.yaml 
> > device-classes:
> > - default: true
> >   lvcreate-options: null
> >   name: ccos-compute
> >   spare-gb: null
> >   stripe: null
> >   stripe-size: ""
> >   thin-pool: null
> >   type: thick
> >   volume-group: ccos-compute
> > - default: true
> >   lvcreate-options: null
> >   name: ccos-database
> >   spare-gb: null
> >   stripe: null
> >   stripe-size: ""
> >   thin-pool: null
> >   type: thick
> >   volume-group: ccos-database
> > socket-name: /run/lvmd/lvmd.sock
> > ```
> 
> As you've already pointed out, it looks like your lvmd.yaml has two device classes marked as default (`default: true`). It should have only one default entry.
> 
> > The lvmd.yaml file generated by the lvm-operator. How to configure this Default flag, I am confused.
> 
> Unfortunately, I can't provide any useful information about the lvm-operator since it's not a TopoLVM project. Maybe you could reach out to the maintainers of the lvm-operator for help?

Yes, i should close the issue.The lvmd.yaml file genrated by the lvm-operator actually.By the way, i still confused about the strcuct deviceclasses of default meaning.
Why can there only be one default? Can you provide some information about TopoLVM regarding this, or help explain it?

**Comment by ushitora-anqou** [comment]
It means the default value of `topolvm.io/device-class` field in StorageClasses using TopoLVM as their provisioners. [The proposal of this feature](https://github.com/topolvm/topolvm/blob/6550055d01ccd98078bad0c755b9580e28374f7b/docs/proposals/multiple-volumegroups.md#option-a-device-class) may help you out. Essentially, each PersistentVolume provisioned by TopoLVM has its own Logical Volume (LV) on a Volume Group (VG), and by specifying a device class in a StorageClass, you can choose which VG should be used to create the LVs.
